### ISSUE TITLE
Cannot connect to multiplayer 

### ISSUE THREAD

**Issue by RzaIX** [TeamFlos/phira#123]
![Screenshot_20230706-164326_Phira](https://github.com/TeamFlos/phira/assets/75961923/4612f231-f366-4614-b903-6cff41cbcfbf)
It just keeps loading

**Comment by atlasveldine** [comment]
Same issue here. Network monitor reports 0KB/s - it doesn't even appear to be attempting a connection at all. Insecure mode results in identical issue. Nothing I've tried seems to resolve this issue. Also, upon updating Phira, all local (ie, downloaded) beatmaps disappeared from the Local list, except ones I've previously downloaded are still showing up as downloaded if I start them from the online beatmap list (Ranked/Unstable)...

Eventually it reports an error: 

> Failed to connect
> 
> Caused by:
>     Connection timed out (os error 110)

This may or may not be related to another issue wherein often, when attempting to download a beatmap, no data is transferred and it just sits on downloading infinitely. In these instances, if I go back, then open the beatmap listing and try again, then repeat this a few times until my network monitor reports data being transferred, eventually it will properly begin and complete the download.

**Comment by sjfhsjfh** [comment]
Which mp server?
The default server is no longer available
