### ISSUE TITLE
软件更新后无法正确列出已有谱面文件列表

### ISSUE THREAD

**Issue by MaTianyi1211** [TeamFlos/phira#126]
于2023/7/7 6：38提交
设备型号：NX531J(努比亚Z11)，6GB+64GB(剩余7.72GB)
操作系统：MIUI 11.0.2稳定版，Android7.1.1，系统已Root
触发条件：将Phira应用从v0.3.3升级为v0.4.0时
v0.3.3未删除用户谱面文件
v0.4.0启动后本地列表中未正确列出谱面文件，却可以在已下载谱面详情页开始游戏
在本地文件地址/data/user/0/org.flos.phira/files/data/charts/download/中可以找到v0.3.3已下载谱面
v0.4.0运行未列出谱面时未出现任何报错，卡顿，闪退等异常现象
最后，感谢TeamFlos对于Phira项目的持续开发与支持，感谢各位开发人员煞费苦心的运营这个项目

**Comment by SuSWhW** [comment]
俺也一样

**Comment by sjfhsjfh** [comment]
See #198
