### ISSUE TITLE
Invalid state

### ISSUE THREAD

**Issue by Lapix0610** [TeamFlos/phira#13]
![Screenshot_20230423-145534_Phira](https://user-images.githubusercontent.com/131575735/233822629-ae190647-6f1a-44a1-83c6-3a3dc8fe6e47.jpg)

1.failed to load resources 
2.invalid state

**Comment by Mivik** [comment]
Could you provide steps to reproduce this?

**Comment by Lapix0610** [comment]
Error pops up when clicking resource pack button or playing song 
![Uploading Screenshot_20230423-154831_Phira.jpg…]()

**Comment by Mivik** [comment]
What's your Android version?

**Comment by Lapix0610** [comment]
Aos11
When screen recording is turned on, it enters the game, but when it is turned off, that error keeps popping up, so I deleted the cache and rebooted, and it was resolved. Thx
