### ISSUE TITLE
Bug in 0.4.0

### ISSUE THREAD

**Issue by RezuMaruyama** [TeamFlos/phira#130]
Chart with shader effect has some trouble that make the charts look zooming out, and the note get bigger then normal size.

**Comment by sjfhsjfh** [comment]
fixed in [e6839e3](https://github.com/TeamFlos/phira/commit/e6839e3a0f82317ed095d1736f6bf8bd6c182565) and [bc042b0](https://github.com/TeamFlos/phira/commit/bc042b02843b33b65fd805a8d863a80c2a7bec2e)
