### ISSUE TITLE
[Bug]更新0.4.0后本地谱面不显示

### ISSUE THREAD

**Issue by XTxiaoting14332** [TeamFlos/phira#134]
进入游戏后，本地谱面显示"空空如也"，但游戏数据没有被清除，如图所示
![-8a315cb171556cb](https://github.com/TeamFlos/phira/assets/96647974/c13651e6-12b0-498c-930d-bbac80b79f5b)

**Comment by ymy139** [comment]
俺也一样

**Comment by sjfhsjfh** [comment]
#126
