### ISSUE TITLE
(Bug) Local beatmaps not showing up v0.4.0

### ISSUE THREAD

**Issue by New5oul** [TeamFlos/phira#137]
beatmaps that were previously downloaded aren't showing in the locals tab (the three maps are recently downloaded after the update). but is taking up space.
![Screenshot_20230710-223808](https://github.com/TeamFlos/phira/assets/134714006/3b189439-066e-4e8d-bc02-0d322075d6a6)
![Screenshot_20230710-223844](https://github.com/TeamFlos/phira/assets/134714006/7d7748dd-928d-475b-bb8d-9a8d317a497b)

**Comment by Apwf** [comment]
同

**Comment by Apwf** [comment]
自此基础上，如果编辑铺面，不修改只点击”保存“，会卡死

**Comment by sjfhsjfh** [comment]
#126
