### ISSUE TITLE
特效铺播放部分特效时出现画面拉伸问题 ( v0.4.0独有? )

### ISSUE THREAD

**Issue by ymy139** [TeamFlos/phira#142]
## 描述
如题，播放特效铺时在部分特效出现的地方会出现竖向拉伸问题
该问题在播放[该铺面](https://www.bilibili.com/video/BV17h411u7sb/?spm_id_from=333.788.video.desc.click)时出现并被本人发现，该问题暂时未经过更多铺面的测试
## 复现操作
1. 下载并播放上述铺面
2. 出现问题
## 问题录屏
*由于截图不能很好的对比问题出现时与正常播放的区别，因此使用录屏*
[链接](https://pan.baidu.com/s/1z4ucH3aIpcKZqdB8z5IBuA?pwd=9ajq)
## 补充说明
设备：vivo S9e
> 型号：V2048A
内核版本：4.14.186+
处理器：Mediatek Dimensity 820
图形处理器：Mali-G57 MC5
运行内存：8+8GB（8G内存+8G ZRAM）
储存：128GB

系统：Orange OS 3
  > 版本：PD2048_A_6.12.5
Android版本：13

**该问题已确认与 激进优化 和 低画质模式 无关**

**Comment by Mivik** [comment]
Fixed in bc042b02843b33b65fd805a8d863a80c2a7bec2e
