### ISSUE TITLE
建议在README文件中添加编译指导。It is recommended to add compilation instructions in the README file

### ISSUE THREAD

**Issue by lubuoren** [TeamFlos/phira#143]
我想把phira上传到AUR（Archlinux User Repo），所以我需要phira的编译流程。
I want to upload phira to AUR (Archlinux User Repo), so I need phira's compilation process.
#### _PS: My English is poor ,so I uses google translate._

**Comment by lubuoren** [comment]
If there are some closed-source codes.I will just upload the binary version.

**Comment by Dage-Hoo** [comment]
没必要吧

**Comment by sjfhsjfh** [comment]
有 anticheat 相关等闭源代码，不予考虑

**Comment by YuevUwU** [comment]
Partially Resolved by [[phira-docs]](https://teamflos.github.io/phira-docs/phira_build_guide/index.html)
And link of phira-docs is currently not in README.md.
Reopen it if the official really care this thing.

NixOS Distribution Attempt: https://github.com/NixOS/nixpkgs/pull/426525
Suggestion to find FFmpeg from pkg-config: #573 
New FFmpeg build artifact position: https://github.com/TeamFlos/prpr-avc-ffmpeg
About the copyright of required assets: #578
