### ISSUE TITLE
TestFlight 链接需要更新

### ISSUE THREAD

**Issue by qingzhixing** [TeamFlos/phira#144]
Testflight显示：
未找到Beta版
 此公共链接的URL 出错。请联系开发者获取更多信息。

**Comment by Pro-Qin** [comment]
**+1**

**Comment by Mivik** [comment]
Testflight member limit (50k) was already reached. You should manage to install ipa instead.

**Comment by qingzhixing** [comment]
> 

Thanks, Iv already installed it by using IPA,thanks for contributions of you guys to Phira,I really like it!!
