### ISSUE TITLE
Account activation email returns an invalid verification link

### ISSUE THREAD

**Issue by surepy** [TeamFlos/phira#146]
# The Problem

Creating an account requires you to verify your email address, however this bug makes the verification process incredibly difficult and unfriendly for the end user.

## What's happening?

The verification email looks like the following:

> From: no-reply \<mivik@noreply.phira.cn\>
> Subject: Activate your account on Phira
> Content-Transfer-Encoding: quoted-printable
>
> Dear surepy:
> 
> Welcome to Phira!
>
> Please visit https://api.phira.cn/activate?code=3Da68736bc-9887-406b-b5e3-1=
> 22b61965772 to activate your account. This link is valid within 10 minutes.
>
> If you've never created an account on Phira, please ignore this mail.

the query string ``code`` is supposed to be an UUID, ``a68736bc-9887-406b-b5e3-122b61965772`` but the server prefixes it with a ``3D`` and chops off part of the UUID by sending it to the next line and replacing it with a ``=``

# The Solution

Remove the somehow prepended ``3D`` and prevent the rest of the UUID from moving to the next line.

**Comment by Mivik** [comment]
Can't reproduce the error and the log in server says the content was totally correct. It might have something to do with your email server.

**Comment by skyrina** [comment]
this also happens to me

**Comment by Mivik** [comment]
The register verification processed is improved. Feel free to reopen this issue tho.
