### ISSUE TITLE
How is multiplayer supposed to work?

### ISSUE THREAD

**Issue by Lesawolf** [TeamFlos/phira#148]
How does multiplayer mode work cuz I don't understand how it works. 
Every time I go to multiplayer it keep loading for to long then it says :

Failed to connect
Caused by:
  Connection time out (os error 110)

So how is this supposed to work , do we need to be connected to the same wifi to play with our friend ? If yes it not very convenient.

**Comment by Mivik** [comment]
The default multiplayer server is down. You could either join a third-party multiplayer server or [set up one on your own](https://github.com/TeamFlos/phira-mp).

**Comment by Lesawolf** [comment]
How to do it then ?
