### ISSUE TITLE
The linux start server report error

### ISSUE THREAD

**Issue by webstorm-dxy** [TeamFlos/phira#149]
My server not have GUI. So it report a error :thread 'main' panicked at 'XOpenDisplay() failed!', /home/mivik/.cargo/git/checkouts/prpr-miniquad-4ecc38303101db59/3c8025b/src/native/linux_x11.rs:854:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by Mivik** [comment]
The phira-main package is a graphical user client. You might be interested with https://github.com/TeamFlos/phira-mp
