### ISSUE TITLE
无法注册

### ISSUE THREAD

**Issue by blufish1234** [TeamFlos/phira#15]
第一次注册说用户名格式不对
第二次直接说邮箱被占用
在登入界面输入密码也没有用

**Comment by blufish1234** [comment]
![2F275EE2-9F1F-45D0-899D-0FFB89A6B90C](https://user-images.githubusercontent.com/97332474/235494657-0c95902e-0c42-41b9-81be-cde6599ce077.png)
![6D613703-9BED-4C19-9EE7-1819AAF38608](https://user-images.githubusercontent.com/97332474/235494681-8e818fa7-4019-4e5e-bdca-f07a6770d3b6.png)

**Comment by xiaoyv404** [comment]
> ![2F275EE2-9F1F-45D0-899D-0FFB89A6B90C](https://user-images.githubusercontent.com/97332474/235494657-0c95902e-0c42-41b9-81be-cde6599ce077.png)
> ![6D613703-9BED-4C19-9EE7-1819AAF38608](https://user-images.githubusercontent.com/97332474/235494681-8e818fa7-4019-4e5e-bdca-f07a6770d3b6.png)
> 

你需要点击在激活邮件中的链接，以此激活这个账号，才能登陆

**Comment by xiaoyv404** [comment]
我认为这应该需要有更好的提示，让用户去激活账号，而不是提示密码或者邮箱错误
