### ISSUE TITLE
The audio in practice mode won't sync automatically 练习模式音频不会自动同步

### ISSUE THREAD

**Issue by contionability** [TeamFlos/phira#150]
在进行练习模式时拖动时间进度条，音频不会被自动同步
（例如在1分钟时暂停，然后将时间拖至2分钟，继续之后音乐仍是在1分钟时的音乐）
并且如果暂停之后直接将时间拖至末尾，可能会出现谱面结束之后谱面音乐仍在播放的问题

**Comment by sjfhsjfh** [comment]
可否提供设备相关信息？

**Comment by contionability** [comment]
用的是红米k50 pro，最新版的系统（之前的系统也是一样的，这段时间无变化）
Phira版本为0.4.0
复刻方法：直接进练习模式，然后先直接点继续一次（或者拖动一下进度条也行），此时音频是正常的（从指定位置开始播放）

然后暂停，拖动一次进度条，再继续（继续之后打不打无所谓，无影响）
重复上述过程（暂停，拖动进度条，继续），一般两次以内即可复现

后面那个bug可能是与蓝牙有关（不太确定，不能稳定复现），在连接蓝牙耳机的时候有小概率复现，不连蓝牙耳机的情况下目前还没测试出来过

开启了低画质模式、激进优化、双击暂停。其余未开启

**Comment by Kuila145** [comment]
我也有同样情况

**Comment by sparrowhe** [comment]
稳定复现 iOS18 Phira 0.6.5 iPad9

似乎与基金优化无关
