### ISSUE TITLE
[Bug] Help with building

### ISSUE THREAD

**Issue by FeyXieXzf** [TeamFlos/phira#152]
When I tried to build this with command `cargo build --release --all-features`, an error appears (I have installed `ffmpeg` which provides the `libavformat.so` library):
```
error: could not find native static library `avformat`, perhaps an -L flag is missing?

error: could not compile `prpr-avc` (lib) due to previous error
```

System Info:
```
system: Arch Linux - up to date
cargo: 1.71.0
rustc: rustc 1.71.0 (8ede3aae2 2023-07-12) (Arch Linux rust 1:1.71.0-1.1)
```

**Comment by FeyXieXzf** [comment]
Moreover, please make phira store its config and data in the `.config` dir, instead of the dir containing itself.
Else if phira is installed in system directories, it can no longer run.

**Comment by FeyXieXzf** [comment]
Moreover, please make phira load config and data from the `AppData`/`.config`/`.local/share` dir instead of the directory containing phira.
Or else phira cannot run if it is installed in system directories.

**Comment by Mivik** [comment]
prpr-avc requires some prebuilt avcodec binaries to run. You can download them [here](https://drive.google.com/file/d/1sUa0EzPrFRqPVt2dkRf2wTz-t3sJPnmM/view?usp=sharing). Unzip the `static-lib` folder and put it into `prpr-avc`

**Comment by Mivik** [comment]
If lucky enough you can just use the one built on mine. Otherwise just reopen this issue and I'll complete the build from source docs.

**Comment by FeyXieXzf** [comment]
Thanks a lot for your help! However I see that building requires some closed source code (`inner.rs`).

**Comment by FeyXieXzf** [comment]
What does it contain? Can you release the file without sensitive information?

**Comment by Mivik** [comment]
> What does it contain? Can you release the file without sensitive information?

That part of code contains record uploading and thus cannot be leaked. You can just build without them, resulting in a version without record uploading ability.
 A full build requires the "closed" feature and inner.rs.

**Comment by FeyXieXzf** [comment]
However I CANNOT build without the `inner.rs` file......

**Comment by Mivik** [comment]
> However I CANNOT build without the `inner.rs` file......

`inner.rs` is required only if the `closed` feature is on. Please post your errors.

**Comment by FeyXieXzf** [comment]
Sorry, my bad. (I add the `--all-features` options to cargo by default...)

**Comment by FeyXieXzf** [comment]
> If lucky enough you can just use the one built on mine. Otherwise just reopen this issue and I'll complete the build from source docs.

Just the last question - how do I build the `static-lib`s? (since I'm writing a PKGBUILD)

**Comment by astro-angelfish** [comment]
> > If lucky enough you can just use the one built on mine. Otherwise just reopen this issue and I'll complete the build from source docs.
> 
> Just the last question - how do I build the `static-lib`s? (since I'm writing a PKGBUILD)

how about just directly pull the binary from the [Release](https://github.com/TeamFlos/phira/releases/tag/v0.4.0) page instead of building from source when something should not be leaked?

**Comment by FeyXieXzf** [comment]
I'm writing a `-git` PKGBUILD...
