### ISSUE TITLE
[Enhancement] Load config & data from user directories

### ISSUE THREAD

**Issue by FeyXieXzf** [TeamFlos/phira#153]
Currently, phira loads its config from where it is located.
This makes phira unable to run if it is installed in system directories.
Please make phira load config and data from the `AppData` / `.config` / `.local/share` dir instead of the directory containing phira.

**Comment by FeyXieXzf** [comment]
Why? I don't see the reason of not implementing this feature. Currently to support this package on AUR, I had to use a really dirty hack (bubblewraps phira to redirect the config dir to a config fir in `.config`).

**Comment by sjfhsjfh** [comment]
Just not planned, if you have the time and energy to implement this feature, please don't hesitate to make a pr
