### ISSUE TITLE
About the register and login things

### ISSUE THREAD

**Issue by ZzeffSmile** [TeamFlos/phira#154]
So i try to register in Phira by create an outlook account and i register success in Phira
but when it ask me to login, it just 
Caused by:
 request failed (400): {''error'':''Email or password is wrong''}
 altho i sign in corectly what my email and password, still cant log in
 *depress*

**Comment by Mivik** [comment]
The register verification processed is improved. Feel free to reopen this issue tho.

**Comment by Alexguy-guy** [comment]
I have the same problem, I did everything ya told me but the outcome is "Failed to log in

Caused by:
    request failed (400): {"error":"Email or password is wrong"}"
I've tried many things can you please help me?

**Comment by thehellofletters** [comment]
I'm trying to make an account on phira but it says unallowed email this is my email esparterosalvador75@gmail.com what do I do
