### ISSUE TITLE
【BUG】Phira v0.4.0 iPad无法导入任何文件

### ISSUE THREAD

**Issue by Wiauy** [TeamFlos/phira#157]
iPad无法更改头像，导入资源包或本地任何文件
同期iOS13.4无此问题但软件无图标显示，且切后台会出现屏闪后黑屏
软件版本：v0.4.0
系统：
iPadOS16.5
iOS13.4
同样问题示例： https://www.bilibili.com/video/BV1Th4y127zZ/?share_source=copy_web&vd_source=1ad446efbb88cca923a95c219b11fcd2

**Comment by Wiauy** [comment]
望尽快修复谢谢

**Comment by Wiauy** [comment]
望尽快修复谢谢

**Comment by CalCobalt** [comment]
同样的，iOS也存在此问题

**Comment by ParaN3xus** [comment]
这不是phira的bug，是签名方式带来的bug。

**Comment by LxHTT** [comment]
这是签名方式导致的。
尝试Apple ID自签

**Comment by sjfhsjfh** [comment]
Not a Phira bug
