### ISSUE TITLE
疑似吃音

### ISSUE THREAD

**Issue by 364hao** [TeamFlos/phira#158]
作者大大好
### 问题
在使用Phisap（Dev）这一软件时，Phira原本应该AP的谱面出现了非常多的断连，疑似吃音
[https://github.com/kvarenzn/phisap/issues/107](url)
主要是集中在86xx cb处，此处全部是Tap，为7k大乱

### 此外
非常抱歉提及其他模拟器，但是事实是在REP里它确实能打出ap
![258613244-b1ecac2c-7dc4-40ee-a86c-4eca9bce23d1](https://github.com/TeamFlos/phira/assets/129530250/75cd3828-64f1-4ea5-a56b-1429dc5aac6c)

**已经确认与低分辨率，音符大小和激进优化无关**

谱面在Phira的位置是未上架-常规，名字为Duplicity Shade

### 补充

1. 手机是OPPO K10x
2. 系统是ColorOS13
3. Android版本13
4. **只有miss**
5. 降低谱面流速后miss数量减少，但不能ap
6. 测试的Phisap（Dev）版本为此Commit[https://github.com/kvarenzn/phisap/issues/url](url)，使用激进算法，配置如下：
![Snipaste_2023-08-10_11-58-20](https://github.com/TeamFlos/phira/assets/129530250/75fd9d15-3ea1-4050-abfd-52d76d73721b)
非常重要的是我将195~198行修改成了下面这样
![Snipaste_2023-08-10_11-59-05](https://github.com/TeamFlos/phira/assets/129530250/6dd4fa62-acc9-4e51-8d52-82077c29efe1)
不过最新版本的Dev我的设备表现并不够优秀，但您也可尝试
7.辛苦了，谢谢！

**Comment by yinlinghunjiang** [comment]
傻卵玩意，开挂开到这了是吧
