### ISSUE TITLE
info.yml无法正确识别

### ISSUE THREAD

**Issue by Apwf** [TeamFlos/phira#160]
#自制资源包

在一切都井井有条时：
     Caused by:
          0:missing yml
          1:No such file or directory (os error 2)

：“？”

//学C的，yaml不会，文件认主 （？
//我该来这里问么......

在用别人的文件调试，所以有不同的hit_fx，求解惑
[白.zip](https://github.com/TeamFlos/phira/files/12320731/default.zip)

**Comment by yinlinghunjiang** [comment]
检查你的资源包的.zip 文件里是否包含 yml 文件

**Comment by Apwf** [comment]
> 有的，请见附带的.zip

**Comment by Mivik** [comment]
> > 有的，请见附带的.zip

压缩包不能包含额外文件夹，所有资源文件需在顶层
