### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Apwf** [TeamFlos/phira#163]
在v3.3更新到v4.0时，本地的曲目消失，但仍能从上架/特殊/未上架/热门找到本地入口：

![03e1201b26356c26076c3b69fe8bf16](https://github.com/TeamFlos/phira/assets/141830208/7ec11d3b-0af0-455b-ac7c-a323730ac727)
![53f686a1cbf689376cc4f86eb89f878](https://github.com/TeamFlos/phira/assets/141830208/4c5ef03a-1f02-4c33-9259-43a0d993acc3)

然而这没什么
删了重下也行

但

编辑铺面，不修改任何，只点击保存，会卡死，只能通过回到桌面杀后台来退出这种状态
![8acf28c0e9f74b6af0d8243f625406c](https://github.com/TeamFlos/phira/assets/141830208/39ed7dd5-5c17-49fd-ac40-abe7676a9b8a)

。。。有什么方法么

**Comment by yinlinghunjiang** [comment]
历史遗留问题（
重新下载

**Comment by Mivik** [comment]
Refer to #134
