### ISSUE TITLE
部分谱缩放异常

### ISSUE THREAD

**Issue by YuSanr** [TeamFlos/phira#164]
在0.3.6正常的铺面
在0.4.0后 铺面有一些特殊的滤镜(会导致整体缩放(有可能是等比例的 有可能是不等比例的 反正看起来非常的怪))
但是在0.3.6不会出现这种问题

顺便建议一下多人游戏的图标位置修改一下 挡在中间很难受

**Comment by Mivik** [comment]
主分支已修复。

以及有没有可能那个按钮是可以拖动的。
