### ISSUE TITLE
访问激活链接后提示“无效的激活码”

### ISSUE THREAD

**Issue by SocialSisterYi** [TeamFlos/phira#168]
使用 qq 邮箱注册，邮件可以正常接收，但点击激活链接，提示`{"error":"无效的激活码"}`

![image](https://github.com/TeamFlos/phira/assets/45892418/18436d3e-ec16-4682-a9ea-ad93df5e18bb)

![image](https://github.com/TeamFlos/phira/assets/45892418/88bfea74-aa77-44c5-81fe-3985dba2e80a)

**Comment by yinlinghunjiang** [comment]
请尝试重新注册
