### ISSUE TITLE
Server is broken

### ISSUE THREAD

**Issue by SteveZMTstudios** [TeamFlos/phira#172]
api.phira.cn returned the http code is 404
The server's signature is dropped.

服务器只会返回404，直接访问也是404
服务器证书掉签了，今天过期
![Screenshot_2023-08-24-09-59-44-554_org flos phira](https://github.com/TeamFlos/phira/assets/98326195/51420b3c-716f-4c1b-9748-79e915de53d0)
![Screenshot_2023-08-24-09-57-18-361_com android chrome](https://github.com/TeamFlos/phira/assets/98326195/36977a4b-5e15-4a7e-a6e8-9f2b5ddcc213)

**Comment by Mivik** [comment]
Fixed

**Comment by SteveZMTstudios** [comment]
server is reopened.
cert is removed...?
