### ISSUE TITLE
华为、荣耀用户无法正常游玩的问题

### ISSUE THREAD

**Issue by Dmocken** [TeamFlos/phira#175]
开发者您好，目前有玩家在游玩过程中出现下列截图的情况，其中荣耀v30居多，其他就是华为旧款的平板，另外少量鸿蒙4.0的用户也遇到了这中情况。
这个错误也并不是开始就有，据其他玩家反馈其为偶尔出现，出现时重启、重装均无效。
这里附上截图：
![97436501cdb60ca02d509141ebc12170](https://github.com/TeamFlos/phira/assets/117455087/09c684b6-4f50-463d-ac61-2cd4eb1d5eeb)
最后感谢开发者的辛苦付出，也希望能尽快修好这个问题。

**Comment by sjfhsjfh** [comment]
#203
