### ISSUE TITLE
[Bug] 播放特效铺时准度（ACC）动画异常

### ISSUE THREAD

**Issue by ymy139** [TeamFlos/phira#191]
## 描述
如题，播放特效铺时ACC没有播放正确的动画
例如在分数隐藏时ACC也需隐藏，但实际并没有隐藏，目前似乎只有结算动画是正常播放的

## 复现操作
1. 播放任意绑定了分数特效的铺面
2. 在分数特效播放时出现问题

## 问题截屏
![6AF0A3D8-71D0-415a-A5D2-D9D33B9E5A53](https://github.com/TeamFlos/phira/assets/117415378/dcca8294-dfb9-40ac-b58d-b4c2350035da.png)
*该铺面 ID 为 10176*

## 期望的行为
ACC应与分数绑定同样的动画

## 补充说明
设备：台式电脑
> CPU：Intel Core i5 10400
  GPU：AMD Radeon RX 550（2GB）
  主板：MSI H510M Bomber (MS-7D22)
  系统：Windows 10 Pro
  内存：16GB DDR4 3200 SDRAM

使用了RTSS与微星小飞机用于显示帧数
**该问题已确认与 激进优化 和 低画质模式 无关**
**该问题似乎与设备无关**

**Comment by Mivik** [comment]
Fixed
