### ISSUE TITLE
Suspected remaining code fragment: upload-downloaded

### ISSUE THREAD

**Issue by YuevUwU** [TeamFlos/phira#196]
### Timeline:
| Date   	| Commit                                   	| Info                                                                                                                	|
|--------	|------------------------------------------	|---------------------------------------------------------------------------------------------------------------------	|
| Apr 9  	| 1a858e0a059debbaae5106b953bd917ba5b66110 	| 新增 `upload-downloaded` 至 <br>`phira/locales/en-US/song.ftl` `phira/locales/zh-CN/song.ftl` `phira/src/scene/song.rs` 	|
| Apr 24 	| 1fa89de4d98373155d2f199f43e38f5453adb7fb 	| 删除 `zh-CN` 和 `song.rs` 中的 `upload-downloaded` 相关引用，然而 **_並未在_** `en-US` **_中被删除_**                            	|
| Oct 23 	| ~ b82e123eb103f5af3372e6c7c8ac766b534c2171 	| (截至Oct 23) 除了 `zh-CN` 與 `zh-TW` 中，皆含有 `upload-downloaded` 疑似未使用之引用                                         	|

### Question
请问是否其应在 `zh-CN` 與 `zh-TW` 中 同步翻译 或 删除/忽略 它们? 亦或是它还有其它用途? 谢谢。

**Comment by Mivik** [comment]
新版中若非本人上传则不会显示按钮，从而没有用到该字段。在 5719381 中移除
