### ISSUE TITLE
0.5.0bug反馈

### ISSUE THREAD

**Issue by Dmocken** [TeamFlos/phira#198]
1.长屏手机在个人空间的“删除账号”功能无法通过上划划出来
![Screenshot_20231025_221716](https://github.com/TeamFlos/phira/assets/117455087/7c4450e2-8f7c-4980-839f-adc67f66c3b1)
2.0.4.0消失的谱面在使用mod的时候软件仍然卡死

https://github.com/TeamFlos/phira/assets/117455087/df58f509-b575-4a3e-a77e-ac6a8c6b2a57

3.0.5.0仍有谱面消失的问题，但是发生几率较小

**Comment by sjfhsjfh** [comment]
辛苦了

**Comment by sjfhsjfh** [comment]
- [x] 删除账号ui问题
- [ ] 旧版本谱面mod问题
- [ ] 升级后谱面丢失（经过更多report和测试发现系0.3.x版本升级至 0.4.x或0.5.x 时会出现）

**Comment by sjfhsjfh** [comment]
#126

**Comment by sjfhsjfh** [comment]
过时
