### ISSUE TITLE
歌曲音量过大，建议减弱音量

### ISSUE THREAD

**Issue by Kyant0** [TeamFlos/phira#199]
1. 预览界面的音量相对较小
2. 游玩时的音量特别大，开最低音量都很大
3. 不同铺面音量不平衡

**Comment by sjfhsjfh** [comment]
有更详细的数值测量吗

我这边暂时没有这种感觉，倒是主界面音乐挺大声的

> 不同铺面音量不平衡

这个似乎是上传者的问题, 不过或许可以考虑以后做个上传时的音量提示功能

**Comment by Kyant0** [comment]
抱歉，没有。我用的是安卓
