### ISSUE TITLE
是否能提供GNU/Linux系统的Releases

### ISSUE THREAD

**Issue by sevente17** [TeamFlos/phira#20]
方便需要的人，不用编译

**Comment by shine-yu-student** [comment]
GNU/Linux is not GUN/Linux

**Comment by sevente17** [comment]
> GNU/Linux 不是 GUN/Linux

Thanks. I didn't check the title carefully.

**Comment by sevente17** [comment]
> GNU/Linux is not GUN/Linux

Thanks. I didn't check the title carefully.

**Comment by Redish101** [comment]
我们将在不久后实现ci自动构建发版，届时将会提供GNU/Linux系统的Releases。
We will soon implement automatic build and release of ci, and will provide Releases for GNU/Linux systems at that time.
