### ISSUE TITLE
为什么它没有在评级中显示我

### ISSUE THREAD

**Issue by IlyaCrab** [TeamFlos/phira#206]
Phira版本：v0.5.0
我播放了这首歌，但评分却写空了，我上网上传了结果，但我不知道该怎么做才能让评分出现在这首歌上。
其他歌曲没有问题
![Screenshot_20231103_154451_org flos phira](https://github.com/TeamFlos/phira/assets/149797727/88ec3fb5-a776-45f7-9d79-e62b66fd3dfe)
![Screenshot_20231103_154459_org flos phira](https://github.com/TeamFlos/phira/assets/149797727/f5508a5c-6de3-4978-ba73-84662539671b)
![Screenshot_20231103_154444_org flos phira](https://github.com/TeamFlos/phira/assets/149797727/962840ad-df74-4250-8b0e-9824c5634c55)

**Comment by sjfhsjfh** [comment]
Check if you're playing in offline mode

Also this might be caused by the server problem today

**Comment by IlyaCrab** [comment]
I was online and replayed the song more than once and still there is no rating, but in other songs everything is fine

**Comment by sjfhsjfh** [comment]
is this still the situation?

**Comment by sjfhsjfh** [comment]
outdated
