### ISSUE TITLE
IOS无法登录

### ISSUE THREAD

**Issue by AzelNiu** [TeamFlos/phira#210]
![微信图片_20231108213053](https://github.com/TeamFlos/phira/assets/130824562/80265fc8-2730-4cdf-904f-600f34708bd9)
![微信图片_20231108213059](https://github.com/TeamFlos/phira/assets/130824562/f62f3c34-cf1e-4317-bfba-a12b5a5b85a3)
如图，打不开用户协议的网页

**Comment by Mivik** [comment]
更新至 0.5.1
