### ISSUE TITLE
Términos de uso y privacidad.

### ISSUE THREAD

**Issue by LaTricolorAAZ** [TeamFlos/phira#211]
No me deja aceptar los términos de uso y privacidad, tengo todo bien, incluída la última versión, tengo mi cuenta activa y he leído los términos y todo lo demás, pero me pide aceptarlos de alguna manera para que me carguen los niveles online, no sé que hacer, ¿Alguna idea? 🤔

**Comment by Mivik** [comment]
Check 0.5.1 update
