### ISSUE TITLE
difficulty logging in

### ISSUE THREAD

**Issue by KaitoChasingclouds** [TeamFlos/phira#212]
Hello, I'm an old phira player who's trying to log back into the game, it says that I have to agree and accept the terms use and privacy policy.. Except that I already done that multiple times, I already read it full but I have no clue on how to accept and agree. Sorry I'm just currently having some issues logging in and I need some help

**Comment by HaHaWTH** [comment]
Click on the Term of Use and Policy buttons,then back.

**Comment by Mivik** [comment]
check v0.5.1 update
