### ISSUE TITLE
May I ask why can't I download this song?- It's says "Invalid token"

### ISSUE THREAD

**Issue by Vviioonn** [TeamFlos/phira#216]
![Screenshot_20231112_094108](https://github.com/TeamFlos/phira/assets/150568272/80d28e14-79bf-4ccb-b175-a52b28c4fe24)
![Screenshot_20231112_094843](https://github.com/TeamFlos/phira/assets/150568272/da832495-d8cb-4a9b-a5f3-8069393a131c)

**Comment by Dage-Hoo** [comment]
log in again

**Comment by Vviioonn** [comment]
> log in again
OMGG!! IT WORKED!! THANKS!!!❤❤❤
