### ISSUE TITLE
游玩时遇到的一些bug

### ISSUE THREAD

**Issue by 24kcsplus** [TeamFlos/phira#22]
环境:安卓11 小米mix2
1.不佩戴耳机游玩铺面会显示failed to load resources，无法游玩，复制错误信息显示成功但剪贴板无内容
(蓝牙耳机，未测试有线耳机，因为我没有Type-C接口的耳机)
2.音符late的话会导致perfect/good提示消失

**Comment by sjfhsjfh** [comment]
Outdated
reopen this issue if necessary
