### ISSUE TITLE
服务器没有问题但是无法登录

### ISSUE THREAD

**Issue by HanakoSakura** [TeamFlos/phira#221]
我和朋友的账号都无法登录。

今天晚上出现的问题（中午还没有）。

尝试在网站上登陆

![Simeji_2023-11-18_20-48-43](https://github.com/TeamFlos/phira/assets/122616035/720b08a4-33fc-4b5c-9478-ff7ccd369194)

在Phira用户界面显示此错误：(v0.5.2)

加载用户信息失败

Caused by:
    request failed (504): <html>
    <head><title>504 Gateway Time-out</title></head>
    <body>
    <center><h1>504 Gateway Time-out</h1></center>
    <hr><center>JSP3/2.0.14</center>
    </body>
    </html>

**Comment by sjfhsjfh** [comment]
服务器过载了

可以看 [b 站动态](https://www.bilibili.com/opus/865324103559544881)
