### ISSUE TITLE
服务器无法连接

### ISSUE THREAD

**Issue by xynsf** [TeamFlos/phira#224]
11月22日，服务器依旧无法链接，或者说是如接，搜索铺面搜得到下不下来
加载歌曲预览失败
{"error":"invalib token"}
下载失败
caused by:
http status client error (400bad request)

**Comment by xynsf** [comment]
搜索功能是正常的，部分铺面有曲绘，部分黑屏，全部无法下载

**Comment by sjfhsjfh** [comment]
服务器问题请移步其他反馈渠道，此处为客户端issue

**Comment by xynsf** [comment]
确实 是客户端问题，但是已经解决了：删掉重下就好了，我这是从0.2直接升到0.5的···
