### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by heloonihao** [TeamFlos/phira#225]
无法登录，无法复制错误，无法滑动查看错误，因为点一下就退出，安卓6.0，红米Note4（nikel）
![Screenshot_2023-11-26-18-31-49-202_org flos phira](https://github.com/TeamFlos/phira/assets/150769256/cb14957f-7eb3-4e71-af19-b85e9cdd9eb2)

**Comment by Mivik** [comment]
请校验系统时间，并尝试更换网络环境
