### ISSUE TITLE
网站上排名显示有误

### ISSUE THREAD

**Issue by henryyuyhy** [TeamFlos/phira#229]
如题
<img width="960" alt="phiramoebug" src="https://github.com/TeamFlos/phira/assets/109945282/84720845-1204-403b-a327-d7f9bb2e5280">
无暇度第一名显示的明显有问题

**Comment by henryyuyhy** [comment]
> 有什么问题
在图片中可见，貌似无暇度第一名的成绩显示的是第三名的数据

**Comment by sjfhsjfh** [comment]
没问题
