### ISSUE TITLE
资源包信息弹窗，点击确认无法关闭

### ISSUE THREAD

**Issue by kaikaibenkai** [TeamFlos/phira#242]
（点击弹窗外围背景仍可正常关闭弹窗）

版本：v0.6.0

![](https://github.com/TeamFlos/phira/assets/99722991/2a1f4d93-ef18-4542-8a99-303f30dad57a)

**Comment by peasoft** [comment]
v0.6.1 仍旧存在

**Comment by sjfhsjfh** [comment]
@Mivik
