### ISSUE TITLE
在Windows上使用键盘打铺面时划键flick会和下一个蓝键tap一起按下

### ISSUE THREAD

**Issue by HanakoSakura** [TeamFlos/phira#248]
出现版本：v0.4.0, v0.5.2, v0.6.1(几乎所以版本？)

就是在尝试接住划键flick时会将下一个note一起判定

如果下一个note不在180ms内则不会判定

**Comment by sjfhsjfh** [comment]
出于公平性和技术性考虑，电脑端自动击打flick和catch且不支持上传成绩
