### ISSUE TITLE
あの、「フィルタ」インタフェースは翻訳されていません。

### ISSUE THREAD

**Issue by HanakoSakura** [TeamFlos/phira#249]
![image](https://github.com/TeamFlos/phira/assets/122616035/fda322e3-6bc5-4f1f-ac72-fa2d3947a8b5)

When I changed the device language to English, the language of the interface was also changed to English.

There are still some parts that have not been fully translated.

awa

**Comment by sjfhsjfh** [comment]
Change the language setting in Phira

**Comment by sjfhsjfh** [comment]
This issue will be closed, reopen if you have any other questions
