### ISSUE TITLE
Cannot log in into the new account

### ISSUE THREAD

**Issue by Nqu77** [TeamFlos/phira#250]
I downloaded phira on my Android, made an account, verified it and got a confirmation message in my mail inbox that it is verified, yet I cannot log in into it in the game. It keeps on saying:
"Failed to log in

Caused by:
    request failed (400): {"error":"Email or password is wrong"}"

And just to clarify, I am sure that both email and password are correct.

**Comment by sjfhsjfh** [comment]
You may check your email, as lower-case is expected

Otherwise I prefer to believe in the computer, or the program

re-open this issue if there's further useful information or any other related question

**Comment by Sillybeing** [comment]
I've been typing my username but still it doesn't let me log in what's going on(/o＼)

**Comment by 1egend-beep** [comment]
I have the same issue as him the email is correct and the password is also correct I checked it 10 times but it has the same problem I even tried this on another account

Failed to log in

Caused by:
    request failed (400): {"error":"Email or password is wrong"}

**Comment by 1egend-beep** [comment]
By "second account "  What I meant is on a second email,

**Comment by Botsitojaen** [comment]
Pensé que era el celular, compre uno nuevo y sigue sin dejar, como puedo iniciar

**Comment by jaijia67** [comment]
It keeps saying Failed to log in.

Caused by:
    request failed (400): {"error":"Email or password is wrong"}

Even tho my password and Gmail is correct
