### ISSUE TITLE
[BUG?]疑似因为对Re:PhiEdit未定义文字事件出错导致Phira闪退/卡死

### ISSUE THREAD

**Issue by dzxgithub** [TeamFlos/phira#252]
电脑phira闪退后最后一段输出: thread 'main' panicked at 'range end index 10 out of range for slice of length 9', prpr/src/core/tween.rs:327:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[93838312.pez.zip](https://github.com/TeamFlos/phira/files/13902281/93838312.pez.zip)
播放上述谱面(或者直接用练习功能拖动)到:267:1/2就闪退/卡死,此处引发崩溃的事件:
![image](https://github.com/TeamFlos/phira/assets/73021142/21e34292-9d6d-49ce-af98-37c793317f3c)

**Comment by dzxgithub** [comment]
完整位置:267:1/2

**Comment by dzxgithub** [comment]
只建议增加检测，cmdysj说这个是未定义，文字事件Back能写但没用，如果你觉得这个算谱师的问题，您也可以直接close此issue,不过我还是更建议在检查谱面文件找到错误缓动的Text事件时拒绝导入

**Comment by sjfhsjfh** [comment]
关于rpe的谱面规范问题，我认为需要有一份文档，在那之前模拟器也很难进行比较全面的适配，近期我可能会推动相关工作，但还需要各方配合，此issue先保持open

**Comment by sjfhsjfh** [comment]
https://github.com/TeamFlos/phira-docs/issues/1
