### ISSUE TITLE
[Bug?] [API] When <a part of the chart name> is used as a keyword, some chart can't be found.

### ISSUE THREAD

**Issue by YuevUwU** [TeamFlos/phira#253]
### Summary
以**谱面名的一部分**作为关键字时，有些谱面无法被找到
When **a part of the chart name** is used as a keyword in the search/query, some chart cannot be found.

### Why to be fixed
Exposure may be reduced for charts whose names contain Japanese characters.

### Example
Division: Regular
Order by: Name asc.

:heavy_check_mark:: Can be found in search
:heavy_multiplication_x:: Cannot be found in search

#### `夜に駆ける` (Expected Chart ID: [2756](https://phira.moe/chart/2756), [5718](https://phira.moe/chart/5718), [5337](https://phira.moe/chart/5337), [12382](https://phira.moe/chart/12382))
:heavy_check_mark:: [`夜に駆ける`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%9C%E3%81%AB%E9%A7%86%E3%81%91%E3%82%8B)、[`夜に駆け`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%9C%E3%81%AB%E9%A7%86%E3%81%91)、[`夜に駆`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%9C%E3%81%AB%E9%A7%86)、[`夜に`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%9C%E3%81%AB)、[`駆け`](https://phira.moe/chart?page=1&order=-name&search=%E9%A7%86%E3%81%91)、[`駆ける`](https://phira.moe/chart?page=1&order=name&search=%E9%A7%86%E3%81%91%E3%82%8B)
:heavy_multiplication_x:: [`夜`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%9C)、[`駆`](https://phira.moe/chart?page=1&order=name&search=%E9%A7%86)、[`ける`](https://phira.moe/chart?page=1&order=-name&search=%E3%81%91%E3%82%8B)

#### `太陽系デスコ` (Expected Chart ID: [8430](https://phira.moe/chart/8430), [5415](https://phira.moe/chart/5415))
:heavy_check_mark:: [`太陽系デスコ`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%AA%E9%99%BD%E7%B3%BB%E3%83%87%E3%82%B9%E3%82%B3)、[`太陽系デス`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%AA%E9%99%BD%E7%B3%BB%E3%83%87%E3%82%B9)、[`太陽系デ`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%AA%E9%99%BD%E7%B3%BB%E3%83%87)、[`デスコ`](https://phira.moe/chart?page=1&order=name&search=%E3%83%87%E3%82%B9%E3%82%B3)、[`デス`](https://phira.moe/chart?page=1&order=name&search=%E3%83%87%E3%82%B9)、[`デ`](https://phira.moe/chart?page=1&order=name&search=%E3%83%87)、[`コ`](https://phira.moe/chart?page=1&order=name&search=%E3%82%B3)
:heavy_multiplication_x:: [`太陽系`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%AA%E9%99%BD%E7%B3%BB)、[`太陽`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%AA%E9%99%BD)、[`太`](https://phira.moe/chart?page=1&order=name&search=%E5%A4%AA)、[`陽`](https://phira.moe/chart?page=1&order=name&search=%E9%99%BD)、[`系`](https://phira.moe/chart?page=1&order=name&search=%E7%B3%BB)、[`陽系`](https://phira.moe/chart?page=1&order=name&search=%E9%99%BD%E7%B3%BB)、[`スコ`](https://phira.moe/chart?page=1&order=name&search=%E3%82%B9%E3%82%B3)、[`ス`](https://phira.moe/chart?page=1&order=name&search=%E3%82%B9)

### Or...
- Does there have some feature like _regex_ or _wild card character_(`*` `?`)?
- And, why does the system seem to be searching for seemingly unrelated charts? (Includes keywords related to its chart info)

**Thanks for your hard work**

**Comment by sjfhsjfh** [comment]
系 [meilisearch](https://www.meilisearch.com/) 搜索引擎对于汉字和假名的支持不够完善，短期内较难有所改善
