### ISSUE TITLE
下好了zip后怎么办

### ISSUE THREAD

**Issue by RENteacher** [TeamFlos/phira#260]
下好了zip后下一步怎么办才能玩

**Comment by blhcm** [comment]
请前往 https://github.com/TeamFlos/phira/releases 下载。

这类问题不要提 Issue，谢谢🙏。

**Comment by fmkli** [comment]
具体请查询万能的搜索引擎
为了问搜索引擎一搜一大把问题专门注册了 GitHub 账号
精神可嘉

**Comment by YuevUwU** [comment]
@RENteacher 
请将您的zip解压缩，具体方式依操作系统而定，也可使用WinRAR或7-Zip等压缩软体
建议您使用解压缩到资料夹功能，倘若无类似选项，为避免将下载文件夹弄乱，也可先将zip移至一新资料夹内再行解压
您应该会找到一执行档：Windows的`phira-main.exe` 或 Linux的`phira-main`，请双击后运行
现在请您在[此处](https://phira.moe/register)注册Phira帐号，切记不要使用Gmail，验证讯息亦可能在垃圾邮件内
接着回到Phira游戏界面后，请点击右上角图标登入，在此道歉目前桌面版本仅支持剪贴板输入
请您开启一个记事本，输入并复制您的邮箱和密码依次贴上至输入框中
在您面前会出现两个按钮 `使用条款`与`隐私政策`，请分别点击他们并回到游戏
接着点击`游玩`按钮，在左侧选择您谱面分类，点进您所希望打的铺面
右下角点击下载图标，倘若下载不稳定或过慢，请取消并重新下载此谱面
点击右下角图标即可游玩

我们推荐您使用手机端游玩以支持上传成绩与更接近Phigros的游戏体验
我们支持Android与iOS，分别提供apk与App Store版本，
以及IPA用于侧载，需要者请移步[F-Unction/phira_ipa](https://github.com/F-Unction/phira_ipa)
具体游玩步骤与上述相似，关于安装手机端等方法请至B站或油管查寻，在此不多赘述。

更多问题请移至[Phira Discord 群组](https://discord.gg/gqpR3bTSsP)
另外感谢您注册Github，相关bug还请先分别以中英文搜索关键字再提出issue
或至Discord群提問

**Comment by Dage-Hoo** [comment]
你都会用github了你不会解压？？？

**Comment by sjfhsjfh** [comment]
有问题再开吧😂
