### ISSUE TITLE
谱面 #15408 会使客户端无法解析玩家游玩记录

### ISSUE THREAD

**Issue by littlekan233** [TeamFlos/phira#270]
经过测试，[谱面 15408](https://phira.moe/chart/15408) 会使玩家的游玩记录无法在客户端展示

结算界面有异常

![Screenshot_20240212_134125_org flos phira](https://github.com/TeamFlos/phira/assets/75866787/adf1a9ff-444d-469a-99e5-df7cf7e3c307)

谱面排行榜展示出错

![Screenshot_20240212_134141_org flos phira](https://github.com/TeamFlos/phira/assets/75866787/df464023-cefb-41c8-9f1f-e9bfbc3d4880)

玩家游玩记录报错

![Screenshot_20240212_134517_org flos phira](https://github.com/TeamFlos/phira/assets/75866787/62281ff9-352d-452a-91e8-df72ed81a946)

网页显示的游玩记录和排行榜正常

![Screenshot_20240212_134546_com android chrome](https://github.com/TeamFlos/phira/assets/75866787/d605e7cf-a52b-43d6-aba6-a9999e608f1f)

![Screenshot_20240212_134647_com android chrome](https://github.com/TeamFlos/phira/assets/75866787/01200642-f53b-4602-9817-03f15878fa1b)

报错信息：
```
加载排行榜失败

Caused by:
    0: error decoding response body: invalid type: null, expected f32 at line 1 column 276
    1: invalid type: null, expected f32 at line 1 column 276
```

```
加载游玩记录失败

Caused by:
    0: error decoding response body: invalid type: null, expected f32 at line 1 column 77
    1: invalid type: null, expected f32 at line 1 column 77
```

**Comment by sjfhsjfh** [comment]
该谱面已删除, 且相关问题已于服务端修复
