### ISSUE TITLE
删去README中的616.sb镜像下载？

### ISSUE THREAD

**Issue by R1Yue** [TeamFlos/phira#272]
因为B站官号说暂停运营，是不是需要删去下载方式

**Comment by ymy139** [comment]
是永久关站（指正）

**Comment by ymy139** [comment]
喜报：616.sb又回来了，但删去了一些下载链接，不过phira还在

**Comment by R1Yue** [comment]
那我close了（）

**Comment by R1Yue** [comment]
这下确实是暂停了www

> 喜报：616.sb又回来了，但删去了一些下载链接，不过phira还在

这下就是暂停了www
