### ISSUE TITLE
打开官谱 V1 谱面将造成崩溃

### ISSUE THREAD

**Issue by XiaoTDM** [TeamFlos/phira#286]
从 Phigros 1.0.0 提取的谱面在 Phira 加载将导致崩溃。
初次认为是 V1 的 "NumOfNotes" 造成错误，但是删除此行后依旧崩溃。
在此附上谱面文件 (Introduction.json)
[Introduction.json](https://github.com/TeamFlos/phira/files/14539484/Introduction.json)

**Comment by sjfhsjfh** [comment]
推测为转谱器问题

不考虑专门针对官谱进行支持

**Comment by YuevUwU** [comment]
Fixed on v0.7.0 by #577
It comment the `assert_eq!(pgr[0].start_time, 0.0);`, won't crash anymore.
Also, `parse_move_events_fv1` is implemented in that PR.
