### ISSUE TITLE
[RPE]建议：在使用sizeControl事件的时候同时改变键的宽度和厚度

### ISSUE THREAD

**Issue by LemoDitary** [TeamFlos/phira#287]
在使用sizeControl事件尝试模拟倾斜轨道时，我对比了rpe侧和phira侧对于同一谱面的处理情况，发现phira侧可能仅仅改变了键的宽度，而没有改变厚度，导致远处的note显示得十分奇怪（如图）。
因此建议phira在使用sizeControl事件的时候同时改变键宽和键的厚度，以确保正常的观感。 
![2](https://github.com/TeamFlos/phira/assets/54306394/7b1c7cb0-2f7f-497f-b33e-77accd2c831d)

**Comment by sjfhsjfh** [comment]
RPE 无技术文档的情况下难以制定统一标准，仅在提交PR时考虑修改

**Comment by sjfhsjfh** [comment]
#293

**Comment by sjfhsjfh** [comment]
#283 重复
