### ISSUE TITLE
Windows Build, with touchscreen. Shouldn't you be able to touch more than one note at a time?

### ISSUE THREAD

**Issue by TurtMaster2000** [TeamFlos/phira#290]
So I recently downloaded the windows build, then went to play Parallel Universe Shifter, and realized I couldn't tap multiple notes at the same time with touchscreen. And you definitely can't do that with a mouse, so I was wondering if this was just my issue, or if this happened to others as well. Thanks!

**Comment by sjfhsjfh** [comment]
#173
