### ISSUE TITLE
想自己编译这个项目

### ISSUE THREAD

**Issue by cuo-ren** [TeamFlos/phira#298]
想看看inner.rs文件

**Comment by cuo-ren** [comment]
能提供一下被忽略的文件吗

**Comment by ParaN3xus** [comment]
不需要这部分文件也能编译pc版本的phira.
编译pc版本的phira对于开发工作已经足够

**Comment by sjfhsjfh** [comment]
编译选项 feature 把closed设置成false编译不包含闭源部分的二进制文件

**Comment by YuevUwU** [comment]
如果您需要的話，非官方流程大概像這樣：https://github.com/YuevUwU/phira/blob/build-doc/BUILD.md
然後我沒有開發經驗，所以只能參考用
我會很快的把非預設的feature提示加上去
(我這個人健忘症)

**Comment by Dage-Hoo** [comment]
inner.rs属于闭源内容，用于维护游戏平衡和版权，不可公开。关闭closed feature也可以正常编译（就是没bgm和立绘）

**Comment by cuo-ren** [comment]
好吧，就是因为release里windows版本没有bgm和立绘，还不计成绩，才想自己编译的

**Comment by sjfhsjfh** [comment]
涉及到版权保护和游戏排行榜公平性，还望理解
