### ISSUE TITLE
Some charts show wrong aspect ratio

### ISSUE THREAD

**Issue by UlyssesZh** [TeamFlos/phira#30]
On devices with wide screen, some charts (e.g. 666, Aurora) appear too narrow.

Example screenshot of a chart with problem (666):
![Screenshot_20230514-000459_Phira](https://github.com/TeamFlos/phira/assets/26196187/2c17d602-d841-4476-a0f8-15e2a3bcd87a)

Example screenshot of a normal chart:
![Screenshot_20230514-000537_Phira](https://github.com/TeamFlos/phira/assets/26196187/51909f79-f420-4626-8035-a90174ab5605)

OS: Android 11
Screen resolution: 3200x1440

**Comment by Mivik** [comment]
Aspect ratio is a configuration that can be specified per-chart. You can see it in the edit section (among the top-right buttons).
