### ISSUE TITLE
[bug]升级版本丢失数据

### ISSUE THREAD

**Issue by rouVling** [TeamFlos/phira#300]
从 0.2.0版本更新到最新（0.6），所有下载的谱面和材质包全部丢失

**Comment by sjfhsjfh** [comment]
在开发者的设备上暂时未能稳定复现

见 #198

**Comment by rouVling** [comment]
可能是升级前的版本记错了？只能确定是第一个要求登录才能查看在线谱面的版本，具体版本号确实不记得了
以及，系统为colorOS 12.1，安卓12。丢失具体症状为，能查看游玩记录和得分，能看到本地导入的谱面，下载的谱面丢失
希望以上信息有助于排查bug
