### ISSUE TITLE
Black Screen when opening 

### ISSUE THREAD

**Issue by RHYTHMGamer0** [TeamFlos/phira#302]
Whenever I open phira It is Just black screen I tried re installing and didn't work it just stuck on black screen I hope this gets fix-ill appreciate it

**Comment by DOHEX** [comment]
me too😭

**Comment by sjfhsjfh** [comment]
Providing device details might be helpful😉

**Comment by RHYTHMGamer0** [comment]
Well I'm using an oppo a5s and install phira latest version is not working when opening it it's just an black screen

**Comment by YuevUwU** [comment]
What if use v7a version? Some devices will crash when opening phira v8a.

**Comment by RHYTHMGamer0** [comment]
I tried to use v7a and it also Black screen when opening

**Comment by DOHEX** [comment]
I reflash the MIUI firmware, then reinstalled the system, and then it could be opened.🫠The problem seems to occur after directly OTA to another system. I have tried clearing data and cache, but it didn't work.

**Comment by TurtMaster2000** [comment]
I have found that using some sort of device emulator in order to trick your device into thinking its something else helps. I'm on a windows, then started using an .APK file and that seemed to help how everything ran by a lot.

**Comment by YuevUwU** [comment]
RHYTHMGamer0 used oppo a5s (Android OS). 
So sorry but I think it doesn't related to PC emulator directly.

**Comment by TurtMaster2000** [comment]
Ok. I can’t really help that, I’m more of a PC emulator guy.

**Comment by smartsh3rw1n** [comment]
I updated my phone to android 15 and it came back randomly.

**Comment by YuevUwU** [comment]
Marked as resolved for #391
Fixed by #462
Merged and it may be fixed in the next release

**Comment by Oersta1rdt** [comment]
Please my device keeps rebooting and doesn't stay on until it's connected to a power source even when battery is at 100 and it overheats

**Comment by YuevUwU** [comment]
> Please my device keeps rebooting and doesn't stay on until it's connected to a power source even when battery is at 100 and it overheats 

Does this only happen when Phira is turned on? 
If so, please open another issue and attach detailed hardware information (phone model, system version, game version). 
If not, please go to a phone repair shop.
