### ISSUE TITLE
[What?]Linux构建版本如果剪切板无任何内容点击输入框会卡死phira

### ISSUE THREAD

**Issue by NuanRMxi** [TeamFlos/phira#312]
Linux构建版本如果剪切板无任何内容点击输入框会卡死phira（终端也会停止输出）

**Comment by YuevUwU** [comment]
能否请教更具体的复现方式呢(虽然好像你跟sjfh似乎很熟，这件事可能它亲自来更好，但这个问题挺有趣的)
好奇的是你如何将剪贴板弄成无内容的
目前尝试了图片数据(无法粘贴成纯文字，从GIMP复制)
以及執行以下命令後拿去登入框都无法复现，就只是把输入框清空罢了
操作系统是Linux Mint 21.3，版本v0.6.2
```sh
xsel -bc
xclip -sel pri < /dev/null
xclip -sel sec < /dev/null
xclip -sel buffer-cut < /dev/null
xclip -sel clip < /dev/null
```

**Comment by NuanRMxi** [comment]
经检查，此问题为xrdp兼容性问题，实际使用虚拟机主屏幕登录桌面环境无法复现，此问题作废
