### ISSUE TITLE
New record songs not updated on phira profile user

### ISSUE THREAD

**Issue by that2456** [TeamFlos/phira#319]
I dont know why all my new record in some chart in phira is not updated on my user profile, for example: my new record in the chart named( Last Dance ) i played is: 881090 point (my new record), and the record in my profile user is 767847 point (my old record) and this proplem still not be fix yet (i rememmber its like 2 month since i played that new record). I hope this issue will be fixed.
![Screenshot (24)](https://github.com/TeamFlos/phira/assets/170817362/a4a83eff-20a6-4d22-a86e-a7f536732f5d)
![Screenshot (25)](https://github.com/TeamFlos/phira/assets/170817362/70aac00f-e791-4ea0-bf02-6097b8fa69e0)

**Comment by sjfhsjfh** [comment]
Playing record on Windows will not be uploaded due consideration to fairness, see #298
