### ISSUE TITLE
从低版本更新到最新后，无法联网

### ISSUE THREAD

**Issue by YesSanSan** [TeamFlos/phira#321]
![Screenshot_20240602_191325_org.flos.phira.jpg](https://github.com/TeamFlos/phira/assets/163381275/661f2b96-7751-4ba4-9787-ea513cbde446)
![Screenshot_20240602_191330_org.flos.phira.jpg](https://github.com/TeamFlos/phira/assets/163381275/a0c24a60-4944-46bf-a85f-7039ebaf98ee)
![Screenshot_20240602_192622_org.flos.phira.jpg](https://github.com/TeamFlos/phira/assets/163381275/f497d68c-02f5-4702-b001-92867e070647)

**Comment by YuevUwU** [comment]
See also: #306
