### ISSUE TITLE
is there an android version?

### ISSUE THREAD

**Issue by TesteTheTestCat** [TeamFlos/phira#322]

**Comment by Crafty-The-Fox** [comment]
yes

**Comment by YuevUwU** [comment]
Okay, I know why he's confused. He/She may not know what is APK.
## How to install Phira
[Download link](https://github.com/TeamFlos/phira/releases/latest)
- `[Phira-windows-vX.X.X.zip](http://phira-windows-vx.x.x.zip/)`: Windows x86_64
- `[Phira-linux-vX.X.X.zip](http://phira-linux-vx.x.x.zip/)`: Linux x86_64
- `[Phira-vX.X.X-arm64-v8a.apk](http://phira-vx.x.x-arm64-v8a.apk/)`: Android ARM 64-bit (Recommended)
- `[Phira-vX.X.X-armeabi-v7a.apk](http://phira-vx.x.x-armeabi-v7a.apk/)`: Android ARM 32-bit (Compatible with 64-bit devices)

If you have problems after downloading v8a like blackscreen during gameplay, please download v7a version. If the game still not working perfectly (even after reboot), please open a new issue with attaching your hardware, Android version, etc. The more detailed the better.

## Install for Android
Just Click the APK file and agree to the installation permissions, that is Android's protection mechanism.

**Comment by TesteTheTestCat** [comment]
thanks!
