### ISSUE TITLE
[IOS] App version on app store is 0.6.1 and not latest.

### ISSUE THREAD

**Issue by Crafty-The-Fox** [TeamFlos/phira#326]
this causes a lot of issues (like annoying popups every single time you open or play a song, saying failing to get leaderboards), but most importantly it dosent allow you to search or download songs.. which is a dealbreaker. The game litereally does not function if you didn't download charts/songs prior to 0.6.2. 

Is there any way to update the app store version or are we stuck with the IPA.....?

**Comment by YuevUwU** [comment]
Actually reopened Testflight, you join by: https://testflight.apple.com/join/6ze92epT
We are sorry that we cannot pass Apple's review at the moment. We should wait until the next version...

**Comment by typed-sigterm** [comment]
dup #317

**Comment by kimsseTheWolf** [comment]
Phira does have an ipa repo, which you can download the 0.6.2 ipa file from its release page and sideload it by yourself. Here is the link:
https://github.com/F-Unction/phira_ipa/releases/tag/phira-0.6.2

**Comment by sjfhsjfh** [comment]
Currently the best choice is to ignore the 0.6.2 version since it did not pass AppStore's app review due to functionality problems.

Should be fixed in the following version.
