### ISSUE TITLE
downloaded failed

### ISSUE THREAD

**Issue by TETRA1002** [TeamFlos/phira#33]
![Screenshot_20230515_122142_Phira](https://github.com/TeamFlos/phira/assets/133621169/9ee0e3bb-3ed1-4314-b381-ecae4842a7d7)
![Screenshot_20230515_122147_Phira](https://github.com/TeamFlos/phira/assets/133621169/805134e9-f76f-4382-96cc-4de3fbd991dd)
![Screenshot_20230515_122152_Phira](https://github.com/TeamFlos/phira/assets/133621169/e42e24a6-6745-4a08-8fe6-1acfc340219d)
I can't play anything except local

**Comment by Mivik** [comment]
Server was out of credit. Should be fixed now.

**Comment by Mivik** [comment]
> Server was out of credit. Should be fixed now.

But it will not live long without stable donation :(

**Comment by JustSimplyKyle** [comment]
Has it died again?
It complained about https://api.phira.cn/ not existing

**Comment by xiaoyv404** [comment]
> Has it died again?
> It complained about https://api.phira.cn/ not existing
> 
> https://c-v.sh/outlandparotid.jpg

me too

**Comment by Mivik** [comment]
> > Has it died again?
> > It complained about https://api.phira.cn/ not existing
> > 
> > https://c-v.sh/outlandparotid.jpg
> 
> me too

The server is up now.

**Comment by Mivik** [comment]
> > > Server was out of credit. Should be fixed now.
> > 
> > But it will not live long without stable donation :(
> 
> How much does a month of server cost

An estimated expense of 4000CNY (~566USD)
