### ISSUE TITLE
TestFlight Beta is full

### ISSUE THREAD

**Issue by Raneing** [TeamFlos/phira#330]
As above, the TestFlight Beta for Phira's iOS 0.6.2 update if currently full and unable to add more users.
The TestFlight link can be found at: https://testflight.apple.com/join/6ze92epT

**Comment by sjfhsjfh** [comment]
iOS developer account is NOT free, and the account for Phira distribution had already been banned once for TestFlight abuse. I'm not going to allow this to happen again. Only unofficial ipa distribution would be active until we have enough time to update and maintain the client.
