### ISSUE TITLE
对于云端分数上传的一些建议

### ISSUE THREAD

**Issue by M100816** [TeamFlos/phira#331]
![Screenshot_2024-06-30-07-59-36-153_com microsoft emmx](https://github.com/TeamFlos/phira/assets/138355736/f0d9d87b-6185-46f7-86ac-328222064be6)
建议允许手动删除多次的成绩，或者自动覆盖低分的成绩，不出现这种一个谱打了好几遍就出现好几遍云分数的情况(σ≧︎▽︎≦︎)σ。

**Comment by sjfhsjfh** [comment]
> 建议允许手动删除多次的成绩

对于排行榜压力较大，暂不考虑

> 自动覆盖低分的成绩

那直接显示最佳成绩即可，没必要展示"最近"了
