### ISSUE TITLE
Is there any reason to ignore some assets files?

### ISSUE THREAD

**Issue by LokKol17** [TeamFlos/phira#333]
# Is there any reason to ignore some assets files?

I was trying to build the app, and it's crashed because it was missing some files (e.g. font.ttf and background.jpg)

So I was wondering if it is there some reason to add them to `.gitignore`.

```
/assets/font.ttf
/assets/charts
/assets/texture
/assets/char.png
/assets/background.jpg
/assets/res
```

(Note: I managed to build with the assets directory of the pre-compiled binaries)

**Comment by typed-sigterm** [comment]
https://github.com/TeamFlos/phira/issues/298#issuecomment-2042218146
