### ISSUE TITLE
[啥？]在搜索谱面时，以"#"开头指定检索谱面ID寻找谱面可以绕过标签、分区限制

### ISSUE THREAD

**Issue by NuanRMxi** [TeamFlos/phira#335]
在使用谱面检索时，以"#"+谱面id搜索谱面可以绕过所有限制，包括但不限于：
上架，未上架，特殊分区限制，所有标签筛选限制（如：我上传的、常规、整活、纯配置）
如果这不是故意为之，请优化检索优先级；若是故意为之，请挂上不是bug的标签后无计划关闭issue

**Comment by sjfhsjfh** [comment]
Expected behavior
