### ISSUE TITLE
[FAQ]静态资源下载 Static Resource Download

### ISSUE THREAD

**Issue by chiming2010** [TeamFlos/phira#338]
phira内铺面无法下载和预览，换成电脑端和ipad端还是不行，已检查过更新，不知道是网络问题还是设备问题

**Comment by chiming2010** [comment]
![Uploading IMG_1372.png…]()

**Comment by chiming2010** [comment]
![IMG_1372](https://github.com/user-attachments/assets/fc30c2b1-6c4f-4c35-91f4-56d5d2798c24)

**Comment by UpKiry** [comment]
俺也一样（）

**Comment by sjfhsjfh** [comment]
当前静态资源下载虽然使用了CDN，但用的cf的免费服务因此回源的流量带宽压力较大，且中国大陆部分地区对于cf的节点访问可能存在一些问题，包括常见的“iOS设备无法下载”的传言也估计为iOS设备默认的DNS设置所致

近期可能会采取一些策略改善，可以关注bilibili官号，此issue保持open

**Comment by NotVeryCreat1ve** [comment]
这问题有了快一个月了

**Comment by chiming2010** [comment]
很久之前就不行了

**Comment by sjfhsjfh** [comment]
现在应该没问题了。
