### ISSUE TITLE
Unable to log in or register

### ISSUE THREAD

**Issue by Flyspeck101** [TeamFlos/phira#339]
When I tried to register an account it gave me an error

Failed to register

Caused by:
    0: error sending request for url (https://api.phira.cn/register): error trying to connect: unexpected EOF (unable to get local issuer certificate)
    1: error trying to connect: unexpected EOF (unable to get local issuer certificate)
    2: unexpected EOF (unable to get local issuer certificate)
    3: error:80000002:system library:file_open:reason(2):providers/implementations/storemgmt/file_store.c:263:calling stat(/usr/local/ssl/certs), error:80000002:system library:file_open:reason(2):providers/implementations/storemgmt/file_store.c:263:calling stat(/usr/local/ssl/certs), error:80000002:system library:file_open:reason(2):providers/implementations/storemgmt/file_store.c:263:calling stat(/usr/local/ssl/certs), error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2092:

So then I made an account from the website, but when I try to log in it still errors

Failed to log in

Caused by:
    0: error sending request for url (https://api.phira.cn/login): error trying to connect: unexpected EOF (unable to get local issuer certificate)
    1: error trying to connect: unexpected EOF (unable to get local issuer certificate)
    2: unexpected EOF (unable to get local issuer certificate)
    3: error:80000002:system library:file_open:reason(2):providers/implementations/storemgmt/file_store.c:263:calling stat(/usr/local/ssl/certs), error:80000002:system library:file_open:reason(2):providers/implementations/storemgmt/file_store.c:263:calling stat(/usr/local/ssl/certs), error:80000002:system library:file_open:reason(2):providers/implementations/storemgmt/file_store.c:263:calling stat(/usr/local/ssl/certs), error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2092:

**Comment by YuevUwU** [comment]
### Solution
1. Enable "Insecure mode" in settings
2. Restart Phira
3. Login

### Possible Reason
[Let's Encrypt Certificate Compatibility](https://letsencrypt.org/docs/certificate-compatibility/)
Devices running lower than Android 7.1.1 (2016↓) or iOS 10 (2016↓, iPad 3↓) will not be able to connect to the Phira API with SSL.

### Keyword
unable to get local issuer certificate

### Related Issue
#225 无法登录

**Comment by Flyspeck101** [comment]
Tysm!

**Comment by lukashovsd** [comment]
I can't register someone help me pls
