### ISSUE TITLE
无法下载谱面 phira.mivik.cn CONNECTION_REFUSED

### ISSUE THREAD

**Issue by xiaoyv404** [TeamFlos/phira#34]
https://phira.mivik.cn/FsSwSM7-ca842WoZN1DBGfo

![Screenshot_2023-05-15-13-27-01-11_d2f71cd433eba6fe82c4c12ffba30ed5.jpg](https://github.com/TeamFlos/phira/assets/63290381/2bc97f7c-0e19-472c-9c39-93bab2b0e866)

**Comment by xiaoyv404** [comment]
duplicate of #33

**Comment by Mivik** [comment]
服务器欠费，已续费
