### ISSUE TITLE
打开Rrhai'il AT Lv.16官谱时报错

### ISSUE THREAD

**Issue by xxsTeamJJBya** [TeamFlos/phira#343]
提示

加载谱面失败

Caused by:
    0: Failed to load resources
    1: unsupported feature: core (codec):unsupported codec

更换其他模拟器没有问题，尽快修复

**Comment by Dage-Hoo** [comment]
phira貌似不支持直接打开官谱，如果你说的官谱是直接从phigros里面拆包出来的话。

**Comment by xxsTeamJJBya** [comment]
> phira貌似不支持直接打开官谱，如果你说的官谱是直接从phigros里面拆包出来的话。

但是同样是拆包出来的DESTRUCTION321AT16、SpasmodicAT16、IgalltaAT16、Distorted FateAT16都能打开，你这么说是不是有点过于牵强了

**Comment by xxsTeamJJBya** [comment]
-

**Comment by YuevUwU** [comment]
虽然我不太熟拆包，能否 ffprobe 那份音档让我们看看?

**Comment by xxsTeamJJBya** [comment]
> 虽然我不太熟拆包，能否 ffprobe 那份音档让我们看看? (可打开和不可打开的)

怎么给你呢
我找找 网上下的 所有拆包都没有问题，除了Rr的AT

**Comment by YuevUwU** [comment]
> 开局先叠甲：官方并不支持(≠支援)在Phira游玩本家谱面，此帮助源于codec问题，为追求Phira之谱面包容性而介入，若官方(TeamFlos和鸽游)觉得不妥，可以将我的留言删除，谢谢

解释安装FFmpeg有些麻烦，这样吧
请到 https://www.videolan.org/vlc/ 下载VLC媒体播放器
用它打开正常的样本和Rr AT，分别查看其 [工具] > [编解码器信息] 与截图后Ctrl-C Ctrl-V 到留言栏。
||虽然你确实可以直接把谱面复制贴上，我只是怕鸽游会生气罢了||

**Comment by sjfhsjfh** [comment]
看似是音频问题

**Comment by xxsTeamJJBya** [comment]
音频被我替换成正常的了，是铺面json的问题

**Comment by xxsTeamJJBya** [comment]
已解决
