### ISSUE TITLE
phira.cn证书过期了

### ISSUE THREAD

**Issue by bGlzdGRlcg** [TeamFlos/phira#348]
![Screenshot_2024-07-25-12-11-20-71.jpg](https://github.com/user-attachments/assets/b5bd6c7d-00a2-4057-ac2f-0c265f44150f)
![Screenshot_2024-07-25-12-12-32-06.jpg](https://github.com/user-attachments/assets/c480c300-1b68-4964-b79e-8a18915fb426)

**Comment by YuevUwU** [comment]
此问题应已解决
