### ISSUE TITLE
无法下载歌曲

### ISSUE THREAD

**Issue by Y1lemon** [TeamFlos/phira#349]
![IMG_0219](https://github.com/user-attachments/assets/c4b5bf9b-db95-482f-9e17-7b4719446588)

全部都是这样

**Comment by sjfhsjfh** [comment]
请尝试重新登陆

**Comment by sjfhsjfh** [comment]
不过确实相关的问题可以考虑改进提示，我另开一个issue吧

**Comment by sjfhsjfh** [comment]
#351
