### ISSUE TITLE
无法正常复制错误信息

### ISSUE THREAD

**Issue by xiaoyv404** [TeamFlos/phira#35]
系统版本 ColorOS 13.0 | Android 13
输入法 gborad

## 预期行为
正确复制错误信息到粘贴板

## 目前
无法正确的复制到粘贴板，虽然会提示复制成功，但是粘贴板内并没有

**Comment by Mivik** [comment]
经检查是 macroquad 未实现

**Comment by Mivik** [comment]
新版本已实现
