### ISSUE TITLE
改进：资源包无法正确加载时的措施

### ISSUE THREAD

**Issue by Dage-Hoo** [TeamFlos/phira#362]
有些时候已经导入的资源包因为某些原因而无法加载导致玩家无法进入资源包管理界面。能否改进一下相关逻辑，让用户能够点进资源包界面，加载错误的资源包处显示无法加载。
![Screenshot_20240808_093045_org flos phira](https://github.com/user-attachments/assets/33376a99-43f1-470d-a8ae-4e34bee5b481)
附图，这里我尝试进入资源包管理页面但是失败了。

**Comment by Dage-Hoo** [comment]
（图貌似崩了）
明白了，问题出在phira的逻辑，导入资源包即使失败也不会删除那些文件夹，我所列举的措施倒是没有必要了。

**Comment by sjfhsjfh** [comment]
fixed in #365
