### ISSUE TITLE
KDE环境下的Phira无法进行登录

### ISSUE THREAD

**Issue by EastCation** [TeamFlos/phira#371]
## 问题描述
在KDE Plasma环境下的Phira无法进行登录，单击登录框只能读取剪贴板；尽管将剪贴板内容全部删除后，单击登录框仍会尝试读取（空内容）

## 运行环境
操作系统： Arch Linux x86_64
内核： Linux 6.10.3-arch1-2
显示器1：1440x900 @ 60 Hz [External] *
显示器2(SyncMaster)：1024x768 @ 85 Hz in 15″ [External]
桌面环境：KDE Plasma 6.1.4
窗口框架：KWin (X11)
处理器：Intel(R) Core(TM) i5-3470 (4) @ 3.60 GHz
显示适配器1：AMD Radeon HD 7450 [Discrete]
显示适配器2：Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics Control]

## 问题截图
![屏幕截图_20240814_083451](https://github.com/user-attachments/assets/3bcf2918-e6a4-4064-a53f-e4e67ff470cb)

**Comment by liquidhelium** [comment]
设计就是如此

**Comment by sjfhsjfh** [comment]
读取剪贴板为预期行为，可参考其他issue

**Comment by EastCation** [comment]
> 读取剪贴板为预期行为，可参考其他issue

但是这样只能账号密码复制到剪贴板才能进行登录操作，并且当剪贴板为读取为空时不应该让用户输入吗？

**Comment by EastCation** [comment]
> 读取剪贴板为预期行为，可参考其他issue

并且我看了一遍 #312 的问题，但是这里的运行环境为***物理硬件***，显示方式为X11（双显示器），进程也不会崩溃（Screen1的htop就是证明）。如果您确定是X11的问题，我可以将它调整为Wayland再试一次。
或者我干脆将此问题报告给KDE社区来解决问题。

**Comment by YuevUwU** [comment]
> > 读取剪贴板为预期行为，可参考其他issue
> 
> 但是这样只能账号密码复制到剪贴板才能进行登录操作，并且当剪贴板为读取为空时不应该让用户输入吗？

关于这个问题主要涉及到 #25 以及 [request_input_full()](https://github.com/TeamFlos/phira/blob/18e14bfece5bdc36b2554f458d63f01e363acc12/prpr/src/scene.rs#L132) 的实现
此实现仰赖 miniquad::window::clipboard_get ，以此作为折衷方案有可能出于 *实现困难* 或 *懒得实现* 等目的，
我相信官方留下 #25 也是知道这问题需要更好的解决方法，
继 #135 后 "interact with IME directly" 也确定成为了目标而**有待其他开发者实现**。
最佳解决方案应该是像一般文本框一样，能输入也能进行 Ctrl-C Ctrl-V Ctrl-A 等直观操作。
依现有做法能改进的方向则是：当剪贴簿读取为空时，留下已输入内容而不贴上。
如果您认为这是您希望的，可以另开一个 issue 作为 enhancement 的目标讨论，或直接提PR。
(但无法保证官方再次*as not planned*...)
**这个问题是 Android 和 iOS 以外之平台共同面对的问题，不单单只针对X11平台。 **
若有任何想法亦可在 #25 讨论

**Comment by EastCation** [comment]
> > > 读取剪贴板为预期行为，可参考其他issue
> > 
> > 
> > 但是这样只能账号密码复制到剪贴板才能进行登录操作，并且当剪贴板为读取为空时不应该让用户输入吗？
> 
> 关于这个问题主要涉及到 #25 以及 [request_input_full()](https://github.com/TeamFlos/phira/blob/18e14bfece5bdc36b2554f458d63f01e363acc12/prpr/src/scene.rs#L132) 的实现 此实现仰赖 miniquad::window::clipboard_get ，以此作为折衷方案有可能出于 _实现困难_ 或 _懒得实现_ 等目的， 我相信官方留下 #25 也是知道这问题需要更好的解决方法， 继 #135 后 "interact with IME directly" 也确定成为了目标而**有待其他开发者实现**。 最佳解决方案应该是像一般文本框一样，能输入也能进行 Ctrl-C Ctrl-V Ctrl-A 等直观操作。 依现有做法能改进的方向则是：当剪贴簿读取为空时，留下已输入内容而不贴上。 如果您认为这是您希望的，可以另开一个 issue 作为 enhancement 的目标讨论，或直接提PR。 (但无法保证官方再次_as not planned_...) **这个问题是 Android 和 iOS 以外之平台共同面对的问题，不单单只针对X11平台。 ** 若有任何想法亦可在 #25 讨论

**我的想法是**：如果剪贴板有内容进行读取并粘贴；若读取到empty或者null则进行break打开输入框让用户进行输入
          因为我学习的语言为Python和Java，直接进行Rust代码修改可能会造成意想不到的后果，还是恳请诸位能够修复这个问题

**Comment by NuanRMxi** [comment]
> > > > 读取剪贴板为预期行为，可参考其他issue
> > > 
> > > 
> > > 但是这样只能账号密码复制到剪贴板才能进行登录操作，并且当剪贴板为读取为空时不应该让用户输入吗？
> > 
> > 
> > 关于这个问题主要涉及到 #25 以及 [request_input_full()](https://github.com/TeamFlos/phira/blob/18e14bfece5bdc36b2554f458d63f01e363acc12/prpr/src/scene.rs#L132) 的实现 此实现仰赖 miniquad::window::clipboard_get ，以此作为折衷方案有可能出于 _实现困难_ 或 _懒得实现_ 等目的， 我相信官方留下 #25 也是知道这问题需要更好的解决方法， 继 #135 后 "interact with IME directly" 也确定成为了目标而**有待其他开发者实现**。 最佳解决方案应该是像一般文本框一样，能输入也能进行 Ctrl-C Ctrl-V Ctrl-A 等直观操作。 依现有做法能改进的方向则是：当剪贴簿读取为空时，留下已输入内容而不贴上。 如果您认为这是您希望的，可以另开一个 issue 作为 enhancement 的目标讨论，或直接提PR。 (但无法保证官方再次_as not planned_...) **这个问题是 Android 和 iOS 以外之平台共同面对的问题，不单单只针对X11平台。 ** 若有任何想法亦可在 #25 讨论
> 
> **我的想法是**：如果剪贴板有内容进行读取并粘贴；若读取到empty或者null则进行break打开输入框让用户进行输入 因为我学习的语言为Python和Java，直接进行Rust代码修改可能会造成意想不到的后果，还是恳请诸位能够修复这个问题

毕竟我们的主要目标还是在手机等移动设备上运行，在电脑上运行理论上**并不是我们的目标**，甚至可能只是为了**方便进行调试**，所以这个问题被搁置多久都十分正常。

**Comment by YuevUwU** [comment]
本 Issue 自 v0.7.0 起支援桌面平台輸入框後不再適用 (#25)
