### ISSUE TITLE
无法正常登陆

### ISSUE THREAD

**Issue by XxOoplslol** [TeamFlos/phira#379]
平台：ios
![IMG_0411](https://github.com/user-attachments/assets/a04f2092-6b61-4ba5-bbcf-b0e939a8a437)
试过开insecure mode ,也试过注册
仍然在登陆/注册时出现错误500

**Comment by adproqwq** [comment]
服务器问题。近期服务器压力较大，近期都会是这样。因为跟隔壁Phigrim共用服务器。

**Comment by NuanRMxi** [comment]
服务器宕机导致的无法登录问题，请前往status.phira.cn确认服务器状态后再尝试重新登录游戏。
