### ISSUE TITLE
Failed to load beatmap 无法加载谱面

### ISSUE THREAD

**Issue by mcLYX** [TeamFlos/phira#38]
![Screenshot_20230515-183954](https://github.com/TeamFlos/phira/assets/109810165/828ba07b-4737-4441-8128-0d7fdd8b030b)
所有谱面均这样,复制
机型LG G8 ThinQ 骁龙855 6+128 安卓12 LGUX9.6
错误信息复制无效

**Comment by Mivik** [comment]
无法获取到音频输出设备。你的音频输出正常吗？重启试过吗？

**Comment by mcLYX** [comment]
> 无法获取到音频输出设备。你的音频输出正常吗？重启试过吗？

音频输出是正常的，重启设备试过了，没用。
之前的prpr是正常的，REPhigros也是正常的，就phira出问题。
另外lchzh3473的也打不开

**Comment by mcLYX** [comment]
> 无法获取到音频输出设备。你的音频输出正常吗？重启试过吗？

已解决
使用ES9218P DAC进行音频解码时加载谱面就会报错，但是主界面音频是正常输出的。
如果关掉DAC进了游戏，再开启DAC就会没声音。
不过虽然找到了问题，但这应该还是个bug（因为主界面音频正常），对自带独立DAC的设备影响很大，尤其是某些还没法关掉的😂以及可能导致自带DAC的耳机也没法使用
