### ISSUE TITLE
Black screen when opening phira

### ISSUE THREAD

**Issue by SergeyYakovlevich** [TeamFlos/phira#391]
i don't really know what happened, but when i open phira it just straight up black screen.

tried to reinstall and delete the cache even the data, but it doesn't work.

**Comment by SergeyYakovlevich** [comment]
if you're wondering what device i used, its Asus ROG phone 6

**Comment by NuanRMxi** [comment]
Do you know how to use adb? If you are capable of using adb, you can use the ‘adb logcat’ command to obtain logs. After using the command, open phira and check the changes in the logs. Thank you!

**Comment by YuevUwU** [comment]
### ADB Logcat Tutorial
#### I. Enable USB debugging

1. Open Settings
2. Navigate to [System] > [About phone] > [Software information]
3. Fast Tap on [Build number] Multiple times
4. Unlock with your device password
5. Navigate to Settings > [System] > [Developer options]
6. Enable USB debugging
(It's danger but useful, so confirm it. You can disable it anytime)

#### II. Use ADB on PC

1. Download [SDK Platform-Tools](https://developer.android.com/tools/releases/platform-tools) for your platform
2. Unzip the downloaded file
3. For **Windows** users, navigate to `platform-tools/` in File Explorer. Click on path field (at top) and input `cmd` and enter. 
Alternative way for **Windows** is Shift+right-click the `platform-tools` folder, choose [Open in Terminal]
For **Mac** users, navigate to **see** `platform-tools/` in Finder, Control-click the folder and choose [Open in Terminal]
For **Linux** or Advanced users, you know how to do that, just `cd` to `path/to/platform-tools`. (or right-click the folder and choose [Open in Terminal] in your file explorer)
4. Find a charging/USB cable, plug in to connect your phone and your PC
5. Your phone will pop up [Use USB for], any mode (including no data transfer) is OK
6. Now, run `./adb logcat > adb.log` in your PC, until it said `- waiting for device -`
7. Your phone will pop up [Allow USB Debugging?] and press [OK]
8. If you see there are any output on PC, open Phira on your phone and wait about 5 seconds
9. Ctrl+C or Control+C to interrupt output on PC

#### III. Upload log on PC

1. Use any text editor such as Notepad or TextEdit to open `platform-tools/adb.log`
2. On **Windows** or **Linux**, Ctrl+A and Ctrl+C to copy all text in the file
On **Mac**, Command+A and Command+C to copy all text in the file
3. Browse [Pastebin](https://pastebin.com/) on PC
4. Ctrl+V or Command+V to paste in the text field, and set Paste Exposure to Unlisted
5. Type name if needed
6. Copy the URL in the top of browser
7. Comment with pasting the URL

**Comment by SergeyYakovlevich** [comment]
thank you, i'll try it later.

**Comment by vpertys** [comment]
i'm also having the same issue, even after uninstalling and rebooting. i'm on rooted custom rom android 14, here's the logcat: [logcat.log](https://github.com/user-attachments/files/16901486/logcat.log)

**Comment by NuanRMxi** [comment]
> i'm also having the same issue, even after uninstalling and rebooting. i'm on rooted custom rom android 14, here's the logcat: [logcat.log](https://github.com/user-attachments/files/16901486/logcat.log)

Thank you for your log. We will process it as soon as possible. What I mean is, if it's within the plan

**Comment by Enderxity** [comment]
having same problem here, running android 15 custom rom
this is the logcat [adb.log](https://github.com/user-attachments/files/17565449/adb.log)

**Comment by corona-32** [comment]
I have found out about the conditions under which this bug occurs.
It only happens when certain settings are turned on. And it is not a developer option. If I factory reset the device, the bug does not occur, but if I restore the settings on the device where the problem occurred after factory reset, the bug occurs again. Restoring the developer options to their default values did not fix the problem.

**Comment by YuevUwU** [comment]
Maybe this command will help you to get the difference by `diff` ^^
```
adb shell settings list global && adb shell settings list system && adb shell settings list secure
```
