### ISSUE TITLE
Can’t login 

### ISSUE THREAD

**Issue by Rchiwzhxe** [TeamFlos/phira#396]
It’s v0.6.4, iOS

**Comment by Gintamashiichan** [comment]
https://github.com/TeamFlos/phira/issues/370#issuecomment-2286195338

**Comment by XingtongHu** [comment]
The Server is down！

**Comment by NuanRMxi** [comment]
This is not a problem with the client, it is caused by server downtime. Please try again multiple times at other times. We are very sorry!

**Comment by XingtongHu** [comment]
OK,I know

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
