### ISSUE TITLE
Failed to fetch TOS and Privacy Policy

### ISSUE THREAD

**Issue by BaronWasTaken** [TeamFlos/phira#403]
Hi, first time playing this so, I just wanna know how to solve this? I can't play anything online cus of this
![Screenshot_20240904_140638_Phira](https://github.com/user-attachments/assets/3b0298f5-4992-4d23-bb31-e23e5eadbf17)

"Failed to fetch Terms of Service and Privacy Policy

Caused by:
    0: failed to fetch terms
    1: failed to fetch terms: 502"

Please help (I really wanna play this), thanks!

**Comment by PhucAnVN** [comment]
When I log in, I also get error 502
![Screenshot_20240904-195713](https://github.com/user-attachments/assets/d399c77f-5ac0-4e89-a9d9-7350997d50e4)

**Comment by PastGone** [comment]
me too.when i open the game ,the game report 502.
but when i check the status of the website,that's good.
so...why?

**Comment by PhucAnVN** [comment]
i dont know , uh... Do I need to record a video to witness it?

Vào 20:47, Th 4, 4 thg 9, 2024 陈不进 ***@***.***> đã viết:

**Comment by NuanRMxi** [comment]
This is our problem, don't worry, it's under repair and may have already been fixed.
这是我们的问题，别急，在修了，可能已经修好了。

**Comment by JMcrafter26** [comment]
It’s not fixed yet 🙁

**Comment by PastGone** [comment]
> It’s not fixed yet 🙁

I don't know, but my game no problem now.

**Comment by NuanRMxi** [comment]
This is still an error caused by intermittent server downtime, not a client issue, even though the [webpage](status.phira.cn) shows that the server is online, which is not the case. This issue will remain open temporarily.
这仍然是由间歇性服务器宕机引起的错误，而不是客户端问题，即使[网页](status.phira.cn)显示服务器联机，但事实并非如此。此问题将暂时保持开放状态。

**Comment by JMcrafter26** [comment]
I just tested it again and it worked this time.

**Comment by PhucAnVN** [comment]
It works!

Vào 16:44, Th 7, 7 thg 9, 2024 John M ***@***.***> đã viết:

**Comment by BaronWasTaken** [comment]
It's fixed! (atleast for me)
