### ISSUE TITLE
failed to login

### ISSUE THREAD

**Issue by axzakoko** [TeamFlos/phira#407]
redownloaded again because phira wouldn't let me search songs for a month now and i now i can't login anymore
did i do something wrong? idk how this works :( i swear i was also using internet connection too this whole time
![Screenshot_20240908_165622_Phira](https://github.com/user-attachments/assets/3ac98d38-3d43-4394-886f-d4fc4b1abbd1)

**Comment by NuanRMxi** [comment]
This is not a problem with the client, it is caused by server downtime. Please try again multiple times at other times. We are very sorry!
