### ISSUE TITLE
Failed to Fetch Terms of Service and Private Policy

### ISSUE THREAD

**Issue by ALASTOR-2K02** [TeamFlos/phira#408]
Caused by:
0: failed to fetch terms
1: failed to fetch terms: 502
![458185279_832577425655091_8272932210499434579_n](https://github.com/user-attachments/assets/ec262caa-3fe3-4c7c-b481-106b689b224b)

**Comment by MyDream132** [comment]
Well I also experienced the same thing so I can't login into my account

**Comment by ALASTOR-2K02** [comment]
I know, right? I don't know what went wrong; I thought it was my network at first.

**Comment by FourK1** [comment]
Same here I have no idea what happened. I got the app about 2-3 days ago and then it just have me this error everywhere. I can't log in, play songs, load songs, and much more hoping they fix this cuz my game is completely broken...

**Comment by catnoteafish** [comment]
Just server failed. Phigrim and Phira service are in same server, so it's unstable. Read [status](status.phira.cn)
