### ISSUE TITLE
Failed to fetch terms of service and privacy policy after logging in

### ISSUE THREAD

**Issue by Yehe-33** [TeamFlos/phira#414]
Failed to fetch Terms of Service and Privacy Policy

Caused by:
    0: failed to fetch terms
    1: failed to fetch terms: 502
![Screenshot_20240926_064643_Phira](https://github.com/user-attachments/assets/f7ee30af-ec7e-4d74-8e7c-861a49688ca4)

**Comment by zeri1122** [comment]
same

**Comment by NuanRMxi** [comment]
Short term errors caused by server downtime, please retry at another time.
