### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by zeri1122** [TeamFlos/phira#415]
Failed to fetch Terms of Service and Privacy Policy

Caused by:
    0: failed to fetch terms
    1: failed to fetch terms: 502
![Screenshot_20240926_162541](https://github.com/user-attachments/assets/de5b982c-42c3-4585-bcc3-e0221463fd69)
![Screenshot_20240926_162630_org flos phira](https://github.com/user-attachments/assets/77e576e8-7ecb-4ed7-ac86-b747ebb58224)

**Comment by NuanRMxi** [comment]
Short term errors caused by server downtime, please retry at another time.
