### ISSUE TITLE
無法更換頭像/歌曲圖片縮圖載入不出來也無法下載

### ISSUE THREAD

**Issue by kuhakuos** [TeamFlos/phira#426]
如題，重新下載過軟體還是一樣rrrr
但看伺服器好像還是正常的在運作，請問這個有解嗎?

![Screenshot_20241008_123201_Phira](https://github.com/user-attachments/assets/808503f9-6028-44d6-833f-82b0d582c8dd)
![Screenshot_20241008_123208_Phira](https://github.com/user-attachments/assets/f862f464-e424-4d22-bc5d-f656faba7521)
![Screenshot_20241008_122603_Phira](https://github.com/user-attachments/assets/83a0d485-bef1-43e3-91ec-3e0f2e8be69c)
![Screenshot_20241008_122615_Phira](https://github.com/user-attachments/assets/feeef489-a939-41bd-a99b-4d35593a1a6e)

**Comment by sjfhsjfh** [comment]
服务器近期正在更新静态服务

**Comment by sjfhsjfh** [comment]
CDN鉴权修好了就好了，不属于客户端问题(x)
先close了

**Comment by kuhakuos** [comment]
感謝解惑!
