### ISSUE TITLE
Bugs in the Windows version

### ISSUE THREAD

**Issue by Aliath0315** [TeamFlos/phira#427]
I am playing Phira on a Windows tablet PC and it barely responds to my taps on the screen. Also, player rankings and RKS do not increase.

**Comment by NuanRMxi** [comment]
There is no score uploading section in the Windows builds, and we've reminded you before you play that you won't be scoring points for this play.

**Comment by NuanRMxi** [comment]
Windows was never very good at supporting touch operations in the first place, and that's partly a Windows problem

**Comment by YuevUwU** [comment]
Similar issue but for multi-touch:
#173 [BUG] Multi-touch is unavailable under Windows

**Comment by NuanRMxi** [comment]
Okay. Repeated issues.

**Comment by YuevUwU** [comment]
Sorry I let your issue closed.
If you mean even a single click doesn't work, please let us know, thank you

**Comment by NuanRMxi** [comment]
> Sorry I let your issue closed. If you mean even a single click doesn't work, please let us know, thank you

That's a Windows problem too, we should ask Microsoft.
