### ISSUE TITLE
API被某些地域墙导致无法下载铺面

### ISSUE THREAD

**Issue by 0x002500** [TeamFlos/phira#453]
![image](https://github.com/user-attachments/assets/6d35908e-7b25-4f82-ae84-b3f68103911a)
![image](https://github.com/user-attachments/assets/dea30b36-d106-49cf-a1e8-10c6a78a3bfe)
![image](https://github.com/user-attachments/assets/f9e5c162-bdcc-4e70-aa82-1fd1b9d512ad)
![image](https://github.com/user-attachments/assets/ce8a48f8-9959-4635-aaba-4ae48fd50314)

**Comment by NuanRMxi** [comment]
你好，请更新Phira，最新版Phira已更新API地址

**Comment by 0x002500** [comment]
好的，谢谢作者解答
