### ISSUE TITLE
note判定时不在判定线上

### ISSUE THREAD

**Issue by Caixuxukun** [TeamFlos/phira#454]
[designant.json](https://github.com/user-attachments/files/18129062/designant.json)

**Comment by NuanRMxi** [comment]
请提供更多的信息，比如：屏幕截图，完整谱面压缩包

**Comment by Caixuxukun** [comment]
https://github.com/user-attachments/assets/59a27f37-3681-4614-ac66-a1fe3db98e19

**Comment by NuanRMxi** [comment]
谱面文件中的瞬时事件（流速）有重叠，导致了流速错误，请尝试修正谱面

**Comment by Caixuxukun** [comment]
[designant-phi.zip](https://github.com/user-attachments/files/18134103/designant-phi.zip)
还是不行

**Comment by NuanRMxi** [comment]
根本没修，还是有重叠的流速事件，这属于谱面的问题，请自行更正谱面的流速事件

**Comment by Caixuxukun** [comment]
具体在pec第几行有重叠

**Comment by NuanRMxi** [comment]
所有流速事件都重叠

**Comment by NuanRMxi** [comment]
你这肯定是什么转谱器转的，谱子全是报错

**Comment by Caixuxukun** [comment]
自己做的转谱器

**Comment by Caixuxukun** [comment]
用lchzh3473的模拟器可以正常显示

**Comment by NuanRMxi** [comment]
谱有问题模拟器怎么处理方法肯定不一致，但是修谱面肯定比修模拟器来得快，因为压根就不是模拟器的事

**Comment by Caixuxukun** [comment]
是不是时间离太近因为精度丢失导致重叠

**Comment by NuanRMxi** [comment]
应该是，时间太近了，要么删一个要么间隔拉大点，还出问题再来反馈

**Comment by Caixuxukun** [comment]
[归档.zip](https://github.com/user-attachments/files/18139397/default.zip)
成这样了

**Comment by NuanRMxi** [comment]
在第0条线的第0拍有流速事件重叠

**Comment by Caixuxukun** [comment]
![IMG_1542](https://github.com/user-attachments/assets/ceb60468-3132-49a2-982f-dd881d3dc734)
没有啊

**Comment by NuanRMxi** [comment]
第12140行与第6行

**Comment by Caixuxukun** [comment]
可以了！
