### ISSUE TITLE
无法进行注册

### ISSUE THREAD

**Issue by HWR20080716** [TeamFlos/phira#46]
我使用outlook邮箱注册时显示注册成功，but没有收到邮件，无报错，请问是不支持outlook，gmail等邮箱吗？

**Comment by HWR20080716** [comment]
且未登录进行下载铺面时报错，复制到剪贴板依然无效![Screenshot_20230518-173344_Phira.jpg](https://github.com/TeamFlos/phira/assets/65950462/db495e30-cf5b-4605-8209-b1c50d5a666a)@![Screenshot_20230518-173334_Phira.jpg](https://github.com/TeamFlos/phira/assets/65950462/a7faad6f-f1b8-4082-8759-a8ef308421c0)![Screenshot_20230518-173529_Phira.jpg](https://github.com/TeamFlos/phira/assets/65950462/1f411d71-da9c-42c3-826c-d188824bbada)

**Comment by HWR20080716** [comment]
如果需要登录才能游玩社区铺面，建议做一个提示

**Comment by Mivik** [comment]
不登录也可以下载，但目前 CDN 欠费且没钱

![Screenshot_2023-05-18-18-25-38-024_com.tencent.mobileqq.jpg](https://github.com/TeamFlos/phira/assets/54128043/cb8ed6db-5781-4ba9-b35c-76c626ccd881)

**Comment by Mivik** [comment]
邮箱递送支持 outlook 和 gmail，请检查垃圾箱

**Comment by HWR20080716** [comment]
outlook总是把一些新邮件当做垃圾邮件（恼）
