### ISSUE TITLE
Windows预编译版发生贴图错误

### ISSUE THREAD

**Issue by RainbowFunny826** [TeamFlos/phira#47]
![image](https://github.com/TeamFlos/phira/assets/53068513/8b1310ac-5ca4-40b0-b2c3-e84fdf0d1679)
如图所示 我自己编译的Linux版本不会这样

**Comment by sjfhsjfh** [comment]
长期未跟进, 视为已解决, 若未解决请 reopen 此 issue 并提供相关信息
