### ISSUE TITLE
下载铺面提示错误

### ISSUE THREAD

**Issue by urbanJava** [TeamFlos/phira#57]
[超级截屏](https://github.com/TeamFlos/phira/assets/109208390/b8219e49-f14b-425b-8b1b-9e84dd1395d5)
[超级截屏](https://github.com/TeamFlos/phira/assets/109208390/912f0744-686c-4c88-adc8-635c13c683f7)
手机型号：vivo V3M A
Android版本：5.1
vivo ROM：Funtouch OS_2.5.1
软件版本号：PD1524B_A_1.18.3

**Comment by Mivik** [comment]
Server is temporarily down
