### ISSUE TITLE
Can't install [armeabi-v7a]

### ISSUE THREAD

**Issue by MaximIce1** [TeamFlos/phira#58]
![Screenshot_2023-05-24-07-55-20-780_com aefyr sai](https://github.com/TeamFlos/phira/assets/79106345/d10a9706-8c47-4708-9f1b-3dca5d7939e5)

**Comment by MaximIce1** [comment]
Tried manually add armeabi-v7a libs, but need port custom libs

**Comment by Mivik** [comment]
Duplicate of https://github.com/TeamFlos/phira/issues/12
