### ISSUE TITLE
error message "Invalid Zip Archive"(0.32)

### ISSUE THREAD

**Issue by yume3neko** [TeamFlos/phira#68]
In Phira ver 0.32, I get an error message "Invalid Zip Archive" and cannot download the chart.

**Comment by yume3neko** [comment]
![Uploading Screenshot_20230526-213732.png…]()

**Comment by yume3neko** [comment]
I no longer get the Invalid Zip Archive error, but
downloading has slowed down considerably.

I also got this error
![Screenshot_20230527-010408](https://github.com/TeamFlos/phira/assets/80351819/93142ab5-187d-4827-99f6-a40e8879d334)

**Comment by yinlinghunjiang** [comment]
update to 0.3.3

**Comment by Mivik** [comment]
Fixed in 0.3.3
