### ISSUE TITLE
Didn't send me email verification

### ISSUE THREAD

**Issue by youziowo** [TeamFlos/phira#72]
It didn't send me email verification
**I tried tree times.**
Bruh

**Comment by didlack** [comment]
Me also can't get gmail verification . I tried five times

**Comment by yinlinghunjiang** [comment]
Check ur junk catalogue or try again

**Comment by Walker37712** [comment]
me too

**Comment by Kuina-chan** [comment]
I haven't received too, checked everywhere

**Comment by yinlinghunjiang** [comment]
well, it might be an network issue...

**Comment by Haano137** [comment]
I've also been trying for the past three days. Does using gmail have anything to do with it I wonder?

**Comment by Haano137** [comment]
Looks like gmail really does seem to be the issue. I recommend other email alternatives instead. From what I've tested, mail.yahoo.com seems to work.

**Comment by lucashuong** [comment]
> From

still cant, even using yahoo

**Comment by Haano137** [comment]
> > 
> 
> still cant, even using yahoo

just check the spam folder

**Comment by yuto0214w** [comment]
Outlook also works, but you still need to check spam folder.

**Comment by tiburonpro** [comment]
Siempre me sale esto cuando quiero poner mi correo 😞
Failed to register.

Caused by:
    request failed (400): {"error":"Email occupied"}
