### ISSUE TITLE
T+ VS Shark chart doesn't start and freezes the app

### ISSUE THREAD

**Issue by helloyanis** [TeamFlos/phira#9]
https://user-images.githubusercontent.com/40769776/233438987-689ae52f-4193-4ac5-bf61-c39cbcbfb782.mp4

Upon trying to play the chart, the loading just gets stuck and I have to exit the app

**Comment by Mivik** [comment]
That's a bug in v0.0.10 causing charts with attachUI unusable. Fixed in the main branch
