### ISSUE TITLE
Didn't send any verification email

### ISSUE THREAD

**Issue by XTD819** [TeamFlos/phira#91]

**Comment by XTD819** [comment]
Cant sign up

**Comment by Normalmeep** [comment]
There's no Email verification code sended onto all of my account, i've tried to register in 4 different account but somehow it still didn't wanted to sign in

**Comment by Mivik** [comment]
Gmail and iCloud has blocked some of the mailing IPs we use (from aliyun)

**Comment by Lesawolf** [comment]
I created an account with outlook and the mail verification still didn't come
