### ISSUE TITLE
使用GitHub Actions进行自动二进制分发

### ISSUE THREAD

**Issue by Hosiyume** [TeamFlos/phira#93]

**Comment by yinlinghunjiang** [comment]
More Info needed

**Comment by StarsDream00** [comment]
> More Info needed

这需要什么信息（

**Comment by Mivik** [comment]
Building the package requires some closed source code and thus making it hard to distribute in CI

**Comment by StarsDream00** [comment]
> Building the package requires some closed source code and thus making it hard to distribute in CI

可以拉取私有仓库

**Comment by FeyXieXzf** [comment]
> Building the package requires some closed source code and thus making it hard to distribute in CI

Then why is it closed-sourced? I don't see the reason of closing source of a clone of a closed-source game.

**Comment by sjfhsjfh** [comment]
@FeyXieXzf 

> Then why is it closed-sourced?

Anticheat
