### ISSUE TITLE
Gmail 和 icloud 邮箱无法注册

### ISSUE THREAD

**Issue by alex080826** [TeamFlos/phira#94]
我的2个Gmail和1个icloud 邮箱再注册后没有收到账户验证邮件，导致无法登录。有什么解决方法吗？谢谢

**Comment by yinlinghunjiang** [comment]
#72

**Comment by alex080826** [comment]
Ya, thanks. It is fine now, I used my 163’s.

**Comment by Mivik** [comment]
Gmail and iCloud has blocked some of the mailing IPs we use (from aliyun)

**Comment by Mivik** [comment]
Duplicate of #91
