### ISSUE TITLE
(Optional)Bad FTL Identifier Spelling in */multiplayer.ftl: "chat-send-failaed" -> "chat-send-failed"

### ISSUE THREAD

**Issue by YuevUwU** [TeamFlos/phira#97]
**⚠️Maybe it is a unsafe change.** 

From commit 579a6593cd3b1de09e3adafe02a29a62b22ca0ce

File affected now:
- [phira/locales/en-US/multiplayer.ftl](https://github.com/TeamFlos/phira/blob/main/phira/locales/en-US/multiplayer.ftl)
- [phira/locales/zh-CN/multiplayer.ftl](https://github.com/TeamFlos/phira/blob/main/phira/locales/zh-CN/multiplayer.ftl)
- [phira/src/mp/panel.rs](https://github.com/TeamFlos/phira/blob/main/phira/src/mp/panel.rs)
(maybe more...)

```
- chat-send-failaed = Failed to send message
+ chat-send-failed = Failed to send message
```

**⚠️Maybe it is a unsafe change.** 

Last check commit: a44e16de709a33217e16779dce60f06160592941

**Comment by Mivik** [comment]
谢谢，在 10d2b9f4835b58ffb0fdd7746c0fcbfd32118c28 中修复
