### ISSUE TITLE
(Suggest)zh-CN Inconsistant/Unusual Translation: "房间主"、"Authorization vs Authentication"(授权 vs 鉴权)

### ISSUE THREAD

**Issue by YuevUwU** [TeamFlos/phira#98]
> 针对Commit: 3f4e816a8128944ef7c48adb7ea59b7092d0d524
###  房间主

> 
> [phira/locales/zh-CN/multiplayer.ftl](https://github.com/TeamFlos/phira/blob/3f4e816a8128944ef7c48adb7ea59b7092d0d524/phira/locales/zh-CN/multiplayer.ftl)
> ```
> ...
> select-chart-host-only = 只有房间主可以选择谱面
> ...
> msg-new-host = `{ $user }` 成为了新的房主
> msg-select-chart = 房主 `{ $user }` 选择了谱面 `{ $chart }` (#{ $id })
> msg-game-start = 房主 `{ $user }` 开始了游戏
> ...
> ```
> 推荐翻译: 
> - 房主 (统一)
> - 房间主人
> 
> 由于本人并非原翻译者/内地人士，在此不发PR

### 授权 vs 鉴权
_**当然，这也可能是故意而为之**_
>
> [phira/locales/zh-CN/multiplayer.ftl](https://github.com/TeamFlos/phira/blob/3f4e816a8128944ef7c48adb7ea59b7092d0d524/phira/locales/zh-CN/multiplayer.ftl)
>
> 根据维基百科[授权 (信息安全)](https://zh.wikipedia.org/zh-cn/%E6%8E%88%E6%AC%8A_(%E8%B3%87%E5%AE%89))条目及[身份验证](https://zh.wikipedia.org/zh-cn/%E8%BA%AB%E4%BB%BD%E9%AA%8C%E8%AF%81)条目
> ```
> 授权（英语：Authorization）一般是指对信息安全或计算机安全相关的资源定义与授予访问权限，尤指存取控制。
> 动词“授权”可指定义访问策略与接受访问。
> 
> 身份验证（英语：Authentication）又称“认证”、“鉴权”，是指通过一定的手段，完成对用户身份的确认。
> ```
> 
> en-US中选用了"Authorization"
> zh-CN中选用了"鉴权"
> 截至2023/06/21，我发布的zh-TW翻译(Beta)暂且引用"鑒權"之翻譯，即"身分驗證"(#100)
> failed被触发的函数名为authorize(位于[phira-mp-client/src/lib.rs](https://github.com/TeamFlos/phira-mp/blob/main/phira-mp-client/src/lib.rs))
> 
> 由于multiplayer功能仍在开发中，且本人没用过Rust，故不下定论。

**Comment by Mivik** [comment]
谢谢，在 c5db8a852af5c508a0ab50382ab40958e949e7d4 中修复
